/* tslint:disable */
/* eslint-disable */
/*
PingData Config - OpenAPI 3.0

This is the PingData Configuration API

The version of the OpenAPI document: 0.1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, isBrowser } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { CipherSecretKeyListResponse } from '../models';
// @ts-ignore
import { CipherSecretKeyResponse } from '../models';
// @ts-ignore
import { Operation } from '../models';
// @ts-ignore
import { UpdateRequest } from '../models';
import { paginate } from "../pagination/paginate";
import type * as buffer from "buffer"
import { requestBeforeHook } from '../requestBeforeHook';
/**
 * CipherSecretKeyApi - axios parameter creator
 * @export
 */
export const CipherSecretKeyApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Returns a list of all Cipher Secret Key objects
         * @param {string} serverInstanceName Name of the Server Instance
         * @param {string} [filter] SCIM filter
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAll: async (serverInstanceName: string, filter?: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'serverInstanceName' is not null or undefined
            assertParamExists('getAll', 'serverInstanceName', serverInstanceName)
            const localVarPath = `/server-instances/{server-instance-name}/cipher-secret-keys`
                .replace(`{${"server-instance-name"}}`, encodeURIComponent(String(serverInstanceName !== undefined ? serverInstanceName : `-server-instance-name-`)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication basicAuth required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)
            if (filter !== undefined) {
                localVarQueryParameter['filter'] = filter;
            }


    
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/server-instances/{server-instance-name}/cipher-secret-keys',
                httpMethod: 'GET'
            });

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Returns a single Cipher Secret Key
         * @param {string} cipherSecretKeyName Name of the Cipher Secret Key
         * @param {string} serverInstanceName Name of the Server Instance
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSingleKey: async (cipherSecretKeyName: string, serverInstanceName: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'cipherSecretKeyName' is not null or undefined
            assertParamExists('getSingleKey', 'cipherSecretKeyName', cipherSecretKeyName)
            // verify required parameter 'serverInstanceName' is not null or undefined
            assertParamExists('getSingleKey', 'serverInstanceName', serverInstanceName)
            const localVarPath = `/server-instances/{server-instance-name}/cipher-secret-keys/{cipher-secret-key-name}`
                .replace(`{${"cipher-secret-key-name"}}`, encodeURIComponent(String(cipherSecretKeyName !== undefined ? cipherSecretKeyName : `-cipher-secret-key-name-`)))
                .replace(`{${"server-instance-name"}}`, encodeURIComponent(String(serverInstanceName !== undefined ? serverInstanceName : `-server-instance-name-`)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication basicAuth required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)

    
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/server-instances/{server-instance-name}/cipher-secret-keys/{cipher-secret-key-name}',
                httpMethod: 'GET'
            });

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Update an existing Cipher Secret Key by name
         * @param {string} cipherSecretKeyName Name of the Cipher Secret Key
         * @param {string} serverInstanceName Name of the Server Instance
         * @param {UpdateRequest} updateRequest Update an existing Cipher Secret Key
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateByName: async (cipherSecretKeyName: string, serverInstanceName: string, updateRequest: UpdateRequest, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'cipherSecretKeyName' is not null or undefined
            assertParamExists('updateByName', 'cipherSecretKeyName', cipherSecretKeyName)
            // verify required parameter 'serverInstanceName' is not null or undefined
            assertParamExists('updateByName', 'serverInstanceName', serverInstanceName)
            // verify required parameter 'updateRequest' is not null or undefined
            assertParamExists('updateByName', 'updateRequest', updateRequest)
            const localVarPath = `/server-instances/{server-instance-name}/cipher-secret-keys/{cipher-secret-key-name}`
                .replace(`{${"cipher-secret-key-name"}}`, encodeURIComponent(String(cipherSecretKeyName !== undefined ? cipherSecretKeyName : `-cipher-secret-key-name-`)))
                .replace(`{${"server-instance-name"}}`, encodeURIComponent(String(serverInstanceName !== undefined ? serverInstanceName : `-server-instance-name-`)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication basicAuth required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)

    
            localVarHeaderParameter['Content-Type'] = 'application/json';


            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                requestBody: updateRequest,
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/server-instances/{server-instance-name}/cipher-secret-keys/{cipher-secret-key-name}',
                httpMethod: 'PATCH'
            });
            localVarRequestOptions.data = serializeDataIfNeeded(updateRequest, localVarRequestOptions, configuration)

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * CipherSecretKeyApi - functional programming interface
 * @export
 */
export const CipherSecretKeyApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = CipherSecretKeyApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Returns a list of all Cipher Secret Key objects
         * @param {CipherSecretKeyApiGetAllRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAll(requestParameters: CipherSecretKeyApiGetAllRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CipherSecretKeyListResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getAll(requestParameters.serverInstanceName, requestParameters.filter, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Returns a single Cipher Secret Key
         * @param {CipherSecretKeyApiGetSingleKeyRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getSingleKey(requestParameters: CipherSecretKeyApiGetSingleKeyRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CipherSecretKeyResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getSingleKey(requestParameters.cipherSecretKeyName, requestParameters.serverInstanceName, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Update an existing Cipher Secret Key by name
         * @param {CipherSecretKeyApiUpdateByNameRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateByName(requestParameters: CipherSecretKeyApiUpdateByNameRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CipherSecretKeyResponse>> {
            const updateRequest: UpdateRequest = {
                operations: requestParameters.operations
            };
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateByName(requestParameters.cipherSecretKeyName, requestParameters.serverInstanceName, updateRequest, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * CipherSecretKeyApi - factory interface
 * @export
 */
export const CipherSecretKeyApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = CipherSecretKeyApiFp(configuration)
    return {
        /**
         * 
         * @summary Returns a list of all Cipher Secret Key objects
         * @param {CipherSecretKeyApiGetAllRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAll(requestParameters: CipherSecretKeyApiGetAllRequest, options?: AxiosRequestConfig): AxiosPromise<CipherSecretKeyListResponse> {
            return localVarFp.getAll(requestParameters, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Returns a single Cipher Secret Key
         * @param {CipherSecretKeyApiGetSingleKeyRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSingleKey(requestParameters: CipherSecretKeyApiGetSingleKeyRequest, options?: AxiosRequestConfig): AxiosPromise<CipherSecretKeyResponse> {
            return localVarFp.getSingleKey(requestParameters, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Update an existing Cipher Secret Key by name
         * @param {CipherSecretKeyApiUpdateByNameRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateByName(requestParameters: CipherSecretKeyApiUpdateByNameRequest, options?: AxiosRequestConfig): AxiosPromise<CipherSecretKeyResponse> {
            return localVarFp.updateByName(requestParameters, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for getAll operation in CipherSecretKeyApi.
 * @export
 * @interface CipherSecretKeyApiGetAllRequest
 */
export type CipherSecretKeyApiGetAllRequest = {
    
    /**
    * Name of the Server Instance
    * @type {string}
    * @memberof CipherSecretKeyApiGetAll
    */
    readonly serverInstanceName: string
    
    /**
    * SCIM filter
    * @type {string}
    * @memberof CipherSecretKeyApiGetAll
    */
    readonly filter?: string
    
}

/**
 * Request parameters for getSingleKey operation in CipherSecretKeyApi.
 * @export
 * @interface CipherSecretKeyApiGetSingleKeyRequest
 */
export type CipherSecretKeyApiGetSingleKeyRequest = {
    
    /**
    * Name of the Cipher Secret Key
    * @type {string}
    * @memberof CipherSecretKeyApiGetSingleKey
    */
    readonly cipherSecretKeyName: string
    
    /**
    * Name of the Server Instance
    * @type {string}
    * @memberof CipherSecretKeyApiGetSingleKey
    */
    readonly serverInstanceName: string
    
}

/**
 * Request parameters for updateByName operation in CipherSecretKeyApi.
 * @export
 * @interface CipherSecretKeyApiUpdateByNameRequest
 */
export type CipherSecretKeyApiUpdateByNameRequest = {
    
    /**
    * Name of the Cipher Secret Key
    * @type {string}
    * @memberof CipherSecretKeyApiUpdateByName
    */
    readonly cipherSecretKeyName: string
    
    /**
    * Name of the Server Instance
    * @type {string}
    * @memberof CipherSecretKeyApiUpdateByName
    */
    readonly serverInstanceName: string
    
} & UpdateRequest

/**
 * CipherSecretKeyApiGenerated - object-oriented interface
 * @export
 * @class CipherSecretKeyApiGenerated
 * @extends {BaseAPI}
 */
export class CipherSecretKeyApiGenerated extends BaseAPI {
    /**
     * 
     * @summary Returns a list of all Cipher Secret Key objects
     * @param {CipherSecretKeyApiGetAllRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CipherSecretKeyApiGenerated
     */
    public getAll(requestParameters: CipherSecretKeyApiGetAllRequest, options?: AxiosRequestConfig) {
        return CipherSecretKeyApiFp(this.configuration).getAll(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Returns a single Cipher Secret Key
     * @param {CipherSecretKeyApiGetSingleKeyRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CipherSecretKeyApiGenerated
     */
    public getSingleKey(requestParameters: CipherSecretKeyApiGetSingleKeyRequest, options?: AxiosRequestConfig) {
        return CipherSecretKeyApiFp(this.configuration).getSingleKey(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Update an existing Cipher Secret Key by name
     * @param {CipherSecretKeyApiUpdateByNameRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CipherSecretKeyApiGenerated
     */
    public updateByName(requestParameters: CipherSecretKeyApiUpdateByNameRequest, options?: AxiosRequestConfig) {
        return CipherSecretKeyApiFp(this.configuration).updateByName(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }
}
