/* tslint:disable */
/* eslint-disable */
/*
PingData Config - OpenAPI 3.0

This is the PingData Configuration API

The version of the OpenAPI document: 0.1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, isBrowser } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { AddJsonAttributeConstraintsRequest } from '../models';
// @ts-ignore
import { EnumjsonAttributeConstraintsSchemaUrn } from '../models';
// @ts-ignore
import { JsonAttributeConstraintsListResponse } from '../models';
// @ts-ignore
import { JsonAttributeConstraintsResponse } from '../models';
// @ts-ignore
import { Operation } from '../models';
// @ts-ignore
import { UpdateRequest } from '../models';
import { paginate } from "../pagination/paginate";
import type * as buffer from "buffer"
import { requestBeforeHook } from '../requestBeforeHook';
/**
 * JsonAttributeConstraintsApi - axios parameter creator
 * @export
 */
export const JsonAttributeConstraintsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Add a new JSON Attribute Constraints to the config
         * @param {AddJsonAttributeConstraintsRequest} addJsonAttributeConstraintsRequest Create a new JSON Attribute Constraints in the config
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addNewConfig: async (addJsonAttributeConstraintsRequest: AddJsonAttributeConstraintsRequest, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'addJsonAttributeConstraintsRequest' is not null or undefined
            assertParamExists('addNewConfig', 'addJsonAttributeConstraintsRequest', addJsonAttributeConstraintsRequest)
            const localVarPath = `/json-attribute-constraints`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication basicAuth required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)

    
            localVarHeaderParameter['Content-Type'] = 'application/json';


            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                requestBody: addJsonAttributeConstraintsRequest,
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/json-attribute-constraints',
                httpMethod: 'POST'
            });
            localVarRequestOptions.data = serializeDataIfNeeded(addJsonAttributeConstraintsRequest, localVarRequestOptions, configuration)

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Delete a JSON Attribute Constraints
         * @param {string} jsonAttributeConstraintsName Name of the JSON Attribute Constraints
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteJsonAttributeConstraints: async (jsonAttributeConstraintsName: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'jsonAttributeConstraintsName' is not null or undefined
            assertParamExists('deleteJsonAttributeConstraints', 'jsonAttributeConstraintsName', jsonAttributeConstraintsName)
            const localVarPath = `/json-attribute-constraints/{json-attribute-constraints-name}`
                .replace(`{${"json-attribute-constraints-name"}}`, encodeURIComponent(String(jsonAttributeConstraintsName !== undefined ? jsonAttributeConstraintsName : `-json-attribute-constraints-name-`)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication basicAuth required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)

    
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/json-attribute-constraints/{json-attribute-constraints-name}',
                httpMethod: 'DELETE'
            });

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Returns a list of all JSON Attribute Constraints objects
         * @param {string} [filter] SCIM filter
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllObjects: async (filter?: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/json-attribute-constraints`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication basicAuth required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)
            if (filter !== undefined) {
                localVarQueryParameter['filter'] = filter;
            }


    
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/json-attribute-constraints',
                httpMethod: 'GET'
            });

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Returns a single JSON Attribute Constraints
         * @param {string} jsonAttributeConstraintsName Name of the JSON Attribute Constraints
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSingleJsonAttributeConstraints: async (jsonAttributeConstraintsName: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'jsonAttributeConstraintsName' is not null or undefined
            assertParamExists('getSingleJsonAttributeConstraints', 'jsonAttributeConstraintsName', jsonAttributeConstraintsName)
            const localVarPath = `/json-attribute-constraints/{json-attribute-constraints-name}`
                .replace(`{${"json-attribute-constraints-name"}}`, encodeURIComponent(String(jsonAttributeConstraintsName !== undefined ? jsonAttributeConstraintsName : `-json-attribute-constraints-name-`)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication basicAuth required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)

    
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/json-attribute-constraints/{json-attribute-constraints-name}',
                httpMethod: 'GET'
            });

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Update an existing JSON Attribute Constraints by name
         * @param {string} jsonAttributeConstraintsName Name of the JSON Attribute Constraints
         * @param {UpdateRequest} updateRequest Update an existing JSON Attribute Constraints
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateByName: async (jsonAttributeConstraintsName: string, updateRequest: UpdateRequest, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'jsonAttributeConstraintsName' is not null or undefined
            assertParamExists('updateByName', 'jsonAttributeConstraintsName', jsonAttributeConstraintsName)
            // verify required parameter 'updateRequest' is not null or undefined
            assertParamExists('updateByName', 'updateRequest', updateRequest)
            const localVarPath = `/json-attribute-constraints/{json-attribute-constraints-name}`
                .replace(`{${"json-attribute-constraints-name"}}`, encodeURIComponent(String(jsonAttributeConstraintsName !== undefined ? jsonAttributeConstraintsName : `-json-attribute-constraints-name-`)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication basicAuth required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)

    
            localVarHeaderParameter['Content-Type'] = 'application/json';


            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                requestBody: updateRequest,
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/json-attribute-constraints/{json-attribute-constraints-name}',
                httpMethod: 'PATCH'
            });
            localVarRequestOptions.data = serializeDataIfNeeded(updateRequest, localVarRequestOptions, configuration)

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * JsonAttributeConstraintsApi - functional programming interface
 * @export
 */
export const JsonAttributeConstraintsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = JsonAttributeConstraintsApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Add a new JSON Attribute Constraints to the config
         * @param {JsonAttributeConstraintsApiAddNewConfigRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async addNewConfig(requestParameters: JsonAttributeConstraintsApiAddNewConfigRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<JsonAttributeConstraintsResponse>> {
            const addJsonAttributeConstraintsRequest: AddJsonAttributeConstraintsRequest = {
            };
            const localVarAxiosArgs = await localVarAxiosParamCreator.addNewConfig(addJsonAttributeConstraintsRequest, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Delete a JSON Attribute Constraints
         * @param {JsonAttributeConstraintsApiDeleteJsonAttributeConstraintsRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteJsonAttributeConstraints(requestParameters: JsonAttributeConstraintsApiDeleteJsonAttributeConstraintsRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteJsonAttributeConstraints(requestParameters.jsonAttributeConstraintsName, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Returns a list of all JSON Attribute Constraints objects
         * @param {JsonAttributeConstraintsApiGetAllObjectsRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAllObjects(requestParameters: JsonAttributeConstraintsApiGetAllObjectsRequest = {}, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<JsonAttributeConstraintsListResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getAllObjects(requestParameters.filter, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Returns a single JSON Attribute Constraints
         * @param {JsonAttributeConstraintsApiGetSingleJsonAttributeConstraintsRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getSingleJsonAttributeConstraints(requestParameters: JsonAttributeConstraintsApiGetSingleJsonAttributeConstraintsRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<JsonAttributeConstraintsResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getSingleJsonAttributeConstraints(requestParameters.jsonAttributeConstraintsName, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Update an existing JSON Attribute Constraints by name
         * @param {JsonAttributeConstraintsApiUpdateByNameRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateByName(requestParameters: JsonAttributeConstraintsApiUpdateByNameRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<JsonAttributeConstraintsResponse>> {
            const updateRequest: UpdateRequest = {
                operations: requestParameters.operations
            };
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateByName(requestParameters.jsonAttributeConstraintsName, updateRequest, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * JsonAttributeConstraintsApi - factory interface
 * @export
 */
export const JsonAttributeConstraintsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = JsonAttributeConstraintsApiFp(configuration)
    return {
        /**
         * 
         * @summary Add a new JSON Attribute Constraints to the config
         * @param {JsonAttributeConstraintsApiAddNewConfigRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addNewConfig(requestParameters: JsonAttributeConstraintsApiAddNewConfigRequest, options?: AxiosRequestConfig): AxiosPromise<JsonAttributeConstraintsResponse> {
            return localVarFp.addNewConfig(requestParameters, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Delete a JSON Attribute Constraints
         * @param {JsonAttributeConstraintsApiDeleteJsonAttributeConstraintsRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteJsonAttributeConstraints(requestParameters: JsonAttributeConstraintsApiDeleteJsonAttributeConstraintsRequest, options?: AxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.deleteJsonAttributeConstraints(requestParameters, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Returns a list of all JSON Attribute Constraints objects
         * @param {JsonAttributeConstraintsApiGetAllObjectsRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllObjects(requestParameters: JsonAttributeConstraintsApiGetAllObjectsRequest = {}, options?: AxiosRequestConfig): AxiosPromise<JsonAttributeConstraintsListResponse> {
            return localVarFp.getAllObjects(requestParameters, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Returns a single JSON Attribute Constraints
         * @param {JsonAttributeConstraintsApiGetSingleJsonAttributeConstraintsRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSingleJsonAttributeConstraints(requestParameters: JsonAttributeConstraintsApiGetSingleJsonAttributeConstraintsRequest, options?: AxiosRequestConfig): AxiosPromise<JsonAttributeConstraintsResponse> {
            return localVarFp.getSingleJsonAttributeConstraints(requestParameters, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Update an existing JSON Attribute Constraints by name
         * @param {JsonAttributeConstraintsApiUpdateByNameRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateByName(requestParameters: JsonAttributeConstraintsApiUpdateByNameRequest, options?: AxiosRequestConfig): AxiosPromise<JsonAttributeConstraintsResponse> {
            return localVarFp.updateByName(requestParameters, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for addNewConfig operation in JsonAttributeConstraintsApi.
 * @export
 * @interface JsonAttributeConstraintsApiAddNewConfigRequest
 */
export type JsonAttributeConstraintsApiAddNewConfigRequest = {
    
} & AddJsonAttributeConstraintsRequest

/**
 * Request parameters for deleteJsonAttributeConstraints operation in JsonAttributeConstraintsApi.
 * @export
 * @interface JsonAttributeConstraintsApiDeleteJsonAttributeConstraintsRequest
 */
export type JsonAttributeConstraintsApiDeleteJsonAttributeConstraintsRequest = {
    
    /**
    * Name of the JSON Attribute Constraints
    * @type {string}
    * @memberof JsonAttributeConstraintsApiDeleteJsonAttributeConstraints
    */
    readonly jsonAttributeConstraintsName: string
    
}

/**
 * Request parameters for getAllObjects operation in JsonAttributeConstraintsApi.
 * @export
 * @interface JsonAttributeConstraintsApiGetAllObjectsRequest
 */
export type JsonAttributeConstraintsApiGetAllObjectsRequest = {
    
    /**
    * SCIM filter
    * @type {string}
    * @memberof JsonAttributeConstraintsApiGetAllObjects
    */
    readonly filter?: string
    
}

/**
 * Request parameters for getSingleJsonAttributeConstraints operation in JsonAttributeConstraintsApi.
 * @export
 * @interface JsonAttributeConstraintsApiGetSingleJsonAttributeConstraintsRequest
 */
export type JsonAttributeConstraintsApiGetSingleJsonAttributeConstraintsRequest = {
    
    /**
    * Name of the JSON Attribute Constraints
    * @type {string}
    * @memberof JsonAttributeConstraintsApiGetSingleJsonAttributeConstraints
    */
    readonly jsonAttributeConstraintsName: string
    
}

/**
 * Request parameters for updateByName operation in JsonAttributeConstraintsApi.
 * @export
 * @interface JsonAttributeConstraintsApiUpdateByNameRequest
 */
export type JsonAttributeConstraintsApiUpdateByNameRequest = {
    
    /**
    * Name of the JSON Attribute Constraints
    * @type {string}
    * @memberof JsonAttributeConstraintsApiUpdateByName
    */
    readonly jsonAttributeConstraintsName: string
    
} & UpdateRequest

/**
 * JsonAttributeConstraintsApiGenerated - object-oriented interface
 * @export
 * @class JsonAttributeConstraintsApiGenerated
 * @extends {BaseAPI}
 */
export class JsonAttributeConstraintsApiGenerated extends BaseAPI {
    /**
     * 
     * @summary Add a new JSON Attribute Constraints to the config
     * @param {JsonAttributeConstraintsApiAddNewConfigRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof JsonAttributeConstraintsApiGenerated
     */
    public addNewConfig(requestParameters: JsonAttributeConstraintsApiAddNewConfigRequest, options?: AxiosRequestConfig) {
        return JsonAttributeConstraintsApiFp(this.configuration).addNewConfig(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Delete a JSON Attribute Constraints
     * @param {JsonAttributeConstraintsApiDeleteJsonAttributeConstraintsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof JsonAttributeConstraintsApiGenerated
     */
    public deleteJsonAttributeConstraints(requestParameters: JsonAttributeConstraintsApiDeleteJsonAttributeConstraintsRequest, options?: AxiosRequestConfig) {
        return JsonAttributeConstraintsApiFp(this.configuration).deleteJsonAttributeConstraints(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Returns a list of all JSON Attribute Constraints objects
     * @param {JsonAttributeConstraintsApiGetAllObjectsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof JsonAttributeConstraintsApiGenerated
     */
    public getAllObjects(requestParameters: JsonAttributeConstraintsApiGetAllObjectsRequest = {}, options?: AxiosRequestConfig) {
        return JsonAttributeConstraintsApiFp(this.configuration).getAllObjects(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Returns a single JSON Attribute Constraints
     * @param {JsonAttributeConstraintsApiGetSingleJsonAttributeConstraintsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof JsonAttributeConstraintsApiGenerated
     */
    public getSingleJsonAttributeConstraints(requestParameters: JsonAttributeConstraintsApiGetSingleJsonAttributeConstraintsRequest, options?: AxiosRequestConfig) {
        return JsonAttributeConstraintsApiFp(this.configuration).getSingleJsonAttributeConstraints(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Update an existing JSON Attribute Constraints by name
     * @param {JsonAttributeConstraintsApiUpdateByNameRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof JsonAttributeConstraintsApiGenerated
     */
    public updateByName(requestParameters: JsonAttributeConstraintsApiUpdateByNameRequest, options?: AxiosRequestConfig) {
        return JsonAttributeConstraintsApiFp(this.configuration).updateByName(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }
}
