/* tslint:disable */
/* eslint-disable */
/*
PingData Config - OpenAPI 3.0

This is the PingData Configuration API

The version of the OpenAPI document: 0.1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, isBrowser } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { Operation } from '../models';
// @ts-ignore
import { PluginRootResponse } from '../models';
// @ts-ignore
import { UpdateRequest } from '../models';
import { paginate } from "../pagination/paginate";
import type * as buffer from "buffer"
import { requestBeforeHook } from '../requestBeforeHook';
/**
 * PluginRootApi - axios parameter creator
 * @export
 */
export const PluginRootApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Returns a single Plugin Root
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSingle: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/plugin-root`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication basicAuth required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)

    
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/plugin-root',
                httpMethod: 'GET'
            });

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Update an existing Plugin Root by name
         * @param {UpdateRequest} updateRequest Update an existing Plugin Root
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateByName: async (updateRequest: UpdateRequest, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'updateRequest' is not null or undefined
            assertParamExists('updateByName', 'updateRequest', updateRequest)
            const localVarPath = `/plugin-root`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication basicAuth required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)

    
            localVarHeaderParameter['Content-Type'] = 'application/json';


            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                requestBody: updateRequest,
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/plugin-root',
                httpMethod: 'PATCH'
            });
            localVarRequestOptions.data = serializeDataIfNeeded(updateRequest, localVarRequestOptions, configuration)

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * PluginRootApi - functional programming interface
 * @export
 */
export const PluginRootApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = PluginRootApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Returns a single Plugin Root
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getSingle(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PluginRootResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getSingle(options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Update an existing Plugin Root by name
         * @param {PluginRootApiUpdateByNameRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateByName(requestParameters: PluginRootApiUpdateByNameRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PluginRootResponse>> {
            const updateRequest: UpdateRequest = {
                operations: requestParameters.operations
            };
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateByName(updateRequest, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * PluginRootApi - factory interface
 * @export
 */
export const PluginRootApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = PluginRootApiFp(configuration)
    return {
        /**
         * 
         * @summary Returns a single Plugin Root
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSingle(options?: AxiosRequestConfig): AxiosPromise<PluginRootResponse> {
            return localVarFp.getSingle(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Update an existing Plugin Root by name
         * @param {PluginRootApiUpdateByNameRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateByName(requestParameters: PluginRootApiUpdateByNameRequest, options?: AxiosRequestConfig): AxiosPromise<PluginRootResponse> {
            return localVarFp.updateByName(requestParameters, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for updateByName operation in PluginRootApi.
 * @export
 * @interface PluginRootApiUpdateByNameRequest
 */
export type PluginRootApiUpdateByNameRequest = {
    
} & UpdateRequest

/**
 * PluginRootApiGenerated - object-oriented interface
 * @export
 * @class PluginRootApiGenerated
 * @extends {BaseAPI}
 */
export class PluginRootApiGenerated extends BaseAPI {
    /**
     * 
     * @summary Returns a single Plugin Root
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PluginRootApiGenerated
     */
    public getSingle(options?: AxiosRequestConfig) {
        return PluginRootApiFp(this.configuration).getSingle(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Update an existing Plugin Root by name
     * @param {PluginRootApiUpdateByNameRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PluginRootApiGenerated
     */
    public updateByName(requestParameters: PluginRootApiUpdateByNameRequest, options?: AxiosRequestConfig) {
        return PluginRootApiFp(this.configuration).updateByName(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }
}
