/*
PingData Config - OpenAPI 3.0

This is the PingData Configuration API

The version of the OpenAPI document: 0.1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AddHttpConnectionHandlerRequestAllOf } from './add-http-connection-handler-request-all-of';
import { EnumconnectionHandlerSslClientAuthPolicyProp } from './enumconnection-handler-ssl-client-auth-policy-prop';
import { EnumldapConnectionHandlerSchemaUrn } from './enumldap-connection-handler-schema-urn';
import { LdapConnectionHandlerShared } from './ldap-connection-handler-shared';

/**
 * @type AddLdapConnectionHandlerRequest
 * @export
 */
export type AddLdapConnectionHandlerRequest = AddHttpConnectionHandlerRequestAllOf & LdapConnectionHandlerShared;


