/*
PingData Config - OpenAPI 3.0

This is the PingData Configuration API

The version of the OpenAPI document: 0.1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AddKeyPairRequestAllOf } from './add-key-pair-request-all-of';
import { EnumkeyPairKeyAlgorithmProp } from './enumkey-pair-key-algorithm-prop';
import { EnumkeyPairSchemaUrn } from './enumkey-pair-schema-urn';
import { KeyPairShared } from './key-pair-shared';

/**
 * @type AddKeyPairRequest
 * @export
 */
export type AddKeyPairRequest = AddKeyPairRequestAllOf & KeyPairShared;


