/*
PingData Config - OpenAPI 3.0

This is the PingData Configuration API

The version of the OpenAPI document: 0.1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AddBlindTrustManagerProviderRequestAllOf } from './add-blind-trust-manager-provider-request-all-of';
import { EnumjvmDefaultTrustManagerProviderSchemaUrn } from './enumjvm-default-trust-manager-provider-schema-urn';
import { JvmDefaultTrustManagerProviderShared } from './jvm-default-trust-manager-provider-shared';

/**
 * @type AddJvmDefaultTrustManagerProviderRequest
 * @export
 */
export type AddJvmDefaultTrustManagerProviderRequest = AddBlindTrustManagerProviderRequestAllOf & JvmDefaultTrustManagerProviderShared;


