/*
PingData Config - OpenAPI 3.0

This is the PingData Configuration API

The version of the OpenAPI document: 0.1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AccountUsabilityIssuesDataSecurityAuditorShared } from './account-usability-issues-data-security-auditor-shared';
import { AddExpiredPasswordDataSecurityAuditorRequestAllOf } from './add-expired-password-data-security-auditor-request-all-of';
import { EnumaccountUsabilityIssuesDataSecurityAuditorSchemaUrn } from './enumaccount-usability-issues-data-security-auditor-schema-urn';
import { EnumdataSecurityAuditorAuditSeverityProp } from './enumdata-security-auditor-audit-severity-prop';

/**
 * @type AddAccountUsabilityIssuesDataSecurityAuditorRequest
 * @export
 */
export type AddAccountUsabilityIssuesDataSecurityAuditorRequest = AccountUsabilityIssuesDataSecurityAuditorShared & AddExpiredPasswordDataSecurityAuditorRequestAllOf;


