/*
PingData Config - OpenAPI 3.0

This is the PingData Configuration API

The version of the OpenAPI document: 0.1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AddNokiaDsExternalServerRequestAllOf } from './add-nokia-ds-external-server-request-all-of';
import { EnumexternalServerTransportMechanismProp } from './enumexternal-server-transport-mechanism-prop';
import { EnumsyslogExternalServerSchemaUrn } from './enumsyslog-external-server-schema-urn';
import { SyslogExternalServerShared } from './syslog-external-server-shared';

/**
 * @type AddSyslogExternalServerRequest
 * @export
 */
export type AddSyslogExternalServerRequest = AddNokiaDsExternalServerRequestAllOf & SyslogExternalServerShared;


