/*
PingData Config - OpenAPI 3.0

This is the PingData Configuration API

The version of the OpenAPI document: 0.1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AddEnvironmentVariablePassphraseProviderRequestAllOf } from './add-environment-variable-passphrase-provider-request-all-of';
import { EnumvaultPassphraseProviderSchemaUrn } from './enumvault-passphrase-provider-schema-urn';
import { VaultPassphraseProviderShared } from './vault-passphrase-provider-shared';

/**
 * @type AddVaultPassphraseProviderRequest
 * @export
 */
export type AddVaultPassphraseProviderRequest = AddEnvironmentVariablePassphraseProviderRequestAllOf & VaultPassphraseProviderShared;


