/*
PingData Config - OpenAPI 3.0

This is the PingData Configuration API

The version of the OpenAPI document: 0.1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AddArgon2dPasswordStorageSchemeRequestAllOf } from './add-argon2d-password-storage-scheme-request-all-of';
import { AzureKeyVaultPasswordStorageSchemeShared } from './azure-key-vault-password-storage-scheme-shared';
import { EnumazureKeyVaultPasswordStorageSchemeSchemaUrn } from './enumazure-key-vault-password-storage-scheme-schema-urn';

/**
 * @type AddAzureKeyVaultPasswordStorageSchemeRequest
 * @export
 */
export type AddAzureKeyVaultPasswordStorageSchemeRequest = AddArgon2dPasswordStorageSchemeRequestAllOf & AzureKeyVaultPasswordStorageSchemeShared;


