/*
PingData Config - OpenAPI 3.0

This is the PingData Configuration API

The version of the OpenAPI document: 0.1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AddUploadToS3LogFileRotationListenerRequestAllOf } from './add-upload-to-s3-log-file-rotation-listener-request-all-of';
import { EnumthirdPartyLogFileRotationListenerSchemaUrn } from './enumthird-party-log-file-rotation-listener-schema-urn';
import { ThirdPartyLogFileRotationListenerShared } from './third-party-log-file-rotation-listener-shared';

/**
 * @type AddThirdPartyLogFileRotationListenerRequest
 * @export
 */
export type AddThirdPartyLogFileRotationListenerRequest = AddUploadToS3LogFileRotationListenerRequestAllOf & ThirdPartyLogFileRotationListenerShared;


