/*
PingData Config - OpenAPI 3.0

This is the PingData Configuration API

The version of the OpenAPI document: 0.1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AddDebugTargetRequestAllOf } from './add-debug-target-request-all-of';
import { DebugTargetShared } from './debug-target-shared';
import { EnumdebugTargetDebugCategoryProp } from './enumdebug-target-debug-category-prop';
import { EnumdebugTargetDebugLevelProp } from './enumdebug-target-debug-level-prop';
import { EnumdebugTargetSchemaUrn } from './enumdebug-target-schema-urn';

/**
 * @type AddDebugTargetRequest
 * @export
 */
export type AddDebugTargetRequest = AddDebugTargetRequestAllOf & DebugTargetShared;


