/*
PingData Config - OpenAPI 3.0

This is the PingData Configuration API

The version of the OpenAPI document: 0.1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AddGenerateServerProfileRecurringTaskRequestAllOf } from './add-generate-server-profile-recurring-task-request-all-of';
import { DelayRecurringTaskShared } from './delay-recurring-task-shared';
import { EnumdelayRecurringTaskSchemaUrn } from './enumdelay-recurring-task-schema-urn';
import { EnumrecurringTaskTaskReturnStateIfTimeoutIsEncounteredProp } from './enumrecurring-task-task-return-state-if-timeout-is-encountered-prop';

/**
 * @type AddDelayRecurringTaskRequest
 * @export
 */
export type AddDelayRecurringTaskRequest = AddGenerateServerProfileRecurringTaskRequestAllOf & DelayRecurringTaskShared;


