/*
PingData Config - OpenAPI 3.0

This is the PingData Configuration API

The version of the OpenAPI document: 0.1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AddTimeLimitLogRotationPolicyRequestAllOf } from './add-time-limit-log-rotation-policy-request-all-of';
import { EnumneverRotateLogRotationPolicySchemaUrn } from './enumnever-rotate-log-rotation-policy-schema-urn';
import { NeverRotateLogRotationPolicyShared } from './never-rotate-log-rotation-policy-shared';

/**
 * @type AddNeverRotateLogRotationPolicyRequest
 * @export
 */
export type AddNeverRotateLogRotationPolicyRequest = AddTimeLimitLogRotationPolicyRequestAllOf & NeverRotateLogRotationPolicyShared;


