/*
PingData Config - OpenAPI 3.0

This is the PingData Configuration API

The version of the OpenAPI document: 0.1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AddBlindTrustManagerProviderRequestAllOf } from './add-blind-trust-manager-provider-request-all-of';
import { BlindTrustManagerProviderShared } from './blind-trust-manager-provider-shared';
import { EnumblindTrustManagerProviderSchemaUrn } from './enumblind-trust-manager-provider-schema-urn';

/**
 * @type AddBlindTrustManagerProviderRequest
 * @export
 */
export type AddBlindTrustManagerProviderRequest = AddBlindTrustManagerProviderRequestAllOf & BlindTrustManagerProviderShared;


