/*
PingData Config - OpenAPI 3.0

This is the PingData Configuration API

The version of the OpenAPI document: 0.1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AggregateIdentityMapperResponse } from './aggregate-identity-mapper-response';
import { DnIdentityMapperResponse } from './dn-identity-mapper-response';
import { EnumthirdPartyIdentityMapperSchemaUrn } from './enumthird-party-identity-mapper-schema-urn';
import { ExactMatchIdentityMapperResponse } from './exact-match-identity-mapper-response';
import { GroovyScriptedIdentityMapperResponse } from './groovy-scripted-identity-mapper-response';
import { MetaMeta } from './meta-meta';
import { MetaUrnPingidentitySchemasConfigurationMessages20 } from './meta-urn-pingidentity-schemas-configuration-messages20';
import { RegularExpressionIdentityMapperResponse } from './regular-expression-identity-mapper-response';
import { ThirdPartyIdentityMapperResponse } from './third-party-identity-mapper-response';

/**
 * @type AddIdentityMapper200Response
 * @export
 */
export type AddIdentityMapper200Response = AggregateIdentityMapperResponse | DnIdentityMapperResponse | ExactMatchIdentityMapperResponse | GroovyScriptedIdentityMapperResponse | RegularExpressionIdentityMapperResponse | ThirdPartyIdentityMapperResponse;


