/*
PingData Config - OpenAPI 3.0

This is the PingData Configuration API

The version of the OpenAPI document: 0.1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AddSyslogJsonAuditLogPublisherRequestAllOf } from './add-syslog-json-audit-log-publisher-request-all-of';
import { EnumjdbcBasedErrorLogPublisherSchemaUrn } from './enumjdbc-based-error-log-publisher-schema-urn';
import { EnumlogPublisherDefaultSeverityProp } from './enumlog-publisher-default-severity-prop';
import { EnumlogPublisherLoggingErrorBehaviorProp } from './enumlog-publisher-logging-error-behavior-prop';
import { JdbcBasedErrorLogPublisherShared } from './jdbc-based-error-log-publisher-shared';

/**
 * @type AddJdbcBasedErrorLogPublisherRequest
 * @export
 */
export type AddJdbcBasedErrorLogPublisherRequest = AddSyslogJsonAuditLogPublisherRequestAllOf & JdbcBasedErrorLogPublisherShared;


