/*
PingData Config - OpenAPI 3.0

This is the PingData Configuration API

The version of the OpenAPI document: 0.1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AddUserRestResourceTypeRequestAllOf } from './add-user-rest-resource-type-request-all-of';
import { EnumgenericRestResourceTypeSchemaUrn } from './enumgeneric-rest-resource-type-schema-urn';
import { GenericRestResourceTypeShared } from './generic-rest-resource-type-shared';

/**
 * @type AddGenericRestResourceTypeRequest
 * @export
 */
export type AddGenericRestResourceTypeRequest = AddUserRestResourceTypeRequestAllOf & GenericRestResourceTypeShared;


