/*
PingData Config - OpenAPI 3.0

This is the PingData Configuration API

The version of the OpenAPI document: 0.1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { EnumsaslMechanismHandlerValidateAccessTokenWhenIDTokenIsAlsoProvidedProp } from './enumsasl-mechanism-handler-validate-access-token-when-idtoken-is-also-provided-prop';
import { EnumthirdPartySaslMechanismHandlerSchemaUrn } from './enumthird-party-sasl-mechanism-handler-schema-urn';
import { MetaMeta } from './meta-meta';
import { MetaUrnPingidentitySchemasConfigurationMessages20 } from './meta-urn-pingidentity-schemas-configuration-messages20';
import { OauthBearerSaslMechanismHandlerResponse } from './oauth-bearer-sasl-mechanism-handler-response';
import { ThirdPartySaslMechanismHandlerResponse } from './third-party-sasl-mechanism-handler-response';
import { UnboundidDeliveredOtpSaslMechanismHandlerResponse } from './unboundid-delivered-otp-sasl-mechanism-handler-response';
import { UnboundidMsChapV2SaslMechanismHandlerResponse } from './unboundid-ms-chap-v2-sasl-mechanism-handler-response';

/**
 * @type AddSaslMechanismHandler200Response
 * @export
 */
export type AddSaslMechanismHandler200Response = OauthBearerSaslMechanismHandlerResponse | ThirdPartySaslMechanismHandlerResponse | UnboundidDeliveredOtpSaslMechanismHandlerResponse | UnboundidMsChapV2SaslMechanismHandlerResponse;


