/*
PingData Config - OpenAPI 3.0

This is the PingData Configuration API

The version of the OpenAPI document: 0.1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AggregateSearchReferenceCriteriaResponse } from './aggregate-search-reference-criteria-response';
import { EnumthirdPartySearchReferenceCriteriaSchemaUrn } from './enumthird-party-search-reference-criteria-schema-urn';
import { MetaMeta } from './meta-meta';
import { MetaUrnPingidentitySchemasConfigurationMessages20 } from './meta-urn-pingidentity-schemas-configuration-messages20';
import { SimpleSearchReferenceCriteriaResponse } from './simple-search-reference-criteria-response';
import { ThirdPartySearchReferenceCriteriaResponse } from './third-party-search-reference-criteria-response';

/**
 * @type AddSearchReferenceCriteria200Response
 * @export
 */
export type AddSearchReferenceCriteria200Response = AggregateSearchReferenceCriteriaResponse | SimpleSearchReferenceCriteriaResponse | ThirdPartySearchReferenceCriteriaResponse;


