/*
PingData Config - OpenAPI 3.0

This is the PingData Configuration API

The version of the OpenAPI document: 0.1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AddTrustedCertificateRequestAllOf } from './add-trusted-certificate-request-all-of';
import { EnumtrustedCertificateSchemaUrn } from './enumtrusted-certificate-schema-urn';
import { TrustedCertificateShared } from './trusted-certificate-shared';

/**
 * @type AddTrustedCertificateRequest
 * @export
 */
export type AddTrustedCertificateRequest = AddTrustedCertificateRequestAllOf & TrustedCertificateShared;


