/*
PingData Config - OpenAPI 3.0

This is the PingData Configuration API

The version of the OpenAPI document: 0.1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface AddDnMapRequestAllOf
 */
export interface AddDnMapRequestAllOf {
    /**
     * Name of the new DN Map
     * @type {string}
     * @memberof AddDnMapRequestAllOf
     */
    'mapName'?: string;
}

