/*
PingData Config - OpenAPI 3.0

This is the PingData Configuration API

The version of the OpenAPI document: 0.1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface AddLoggingChangeSubscriptionHandlerRequestAllOf
 */
export interface AddLoggingChangeSubscriptionHandlerRequestAllOf {
    /**
     * Name of the new Change Subscription Handler
     * @type {string}
     * @memberof AddLoggingChangeSubscriptionHandlerRequestAllOf
     */
    'handlerName'?: string;
}

