/*
PingData Config - OpenAPI 3.0

This is the PingData Configuration API

The version of the OpenAPI document: 0.1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AddRandomPasswordGeneratorRequestAllOf } from './add-random-password-generator-request-all-of';
import { EnumgroovyScriptedPasswordGeneratorSchemaUrn } from './enumgroovy-scripted-password-generator-schema-urn';
import { GroovyScriptedPasswordGeneratorShared } from './groovy-scripted-password-generator-shared';

/**
 * @type AddGroovyScriptedPasswordGeneratorRequest
 * @export
 */
export type AddGroovyScriptedPasswordGeneratorRequest = AddRandomPasswordGeneratorRequestAllOf & GroovyScriptedPasswordGeneratorShared;


