/*
PingData Config - OpenAPI 3.0

This is the PingData Configuration API

The version of the OpenAPI document: 0.1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AddNoOperationFailureLockoutActionRequestAllOf } from './add-no-operation-failure-lockout-action-request-all-of';
import { EnumlockAccountFailureLockoutActionSchemaUrn } from './enumlock-account-failure-lockout-action-schema-urn';
import { LockAccountFailureLockoutActionShared } from './lock-account-failure-lockout-action-shared';

/**
 * @type AddLockAccountFailureLockoutActionRequest
 * @export
 */
export type AddLockAccountFailureLockoutActionRequest = AddNoOperationFailureLockoutActionRequestAllOf & LockAccountFailureLockoutActionShared;


