/*
PingData Config - OpenAPI 3.0

This is the PingData Configuration API

The version of the OpenAPI document: 0.1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AddVelocityTemplateLoaderRequestAllOf } from './add-velocity-template-loader-request-all-of';
import { EnumvelocityTemplateLoaderSchemaUrn } from './enumvelocity-template-loader-schema-urn';
import { VelocityTemplateLoaderShared } from './velocity-template-loader-shared';

/**
 * @type AddVelocityTemplateLoaderRequest
 * @export
 */
export type AddVelocityTemplateLoaderRequest = AddVelocityTemplateLoaderRequestAllOf & VelocityTemplateLoaderShared;


