/*
PingData Config - OpenAPI 3.0

This is the PingData Configuration API

The version of the OpenAPI document: 0.1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AddHttpConnectionHandlerRequest } from './add-http-connection-handler-request';
import { AddJmxConnectionHandlerRequest } from './add-jmx-connection-handler-request';
import { AddLdapConnectionHandlerRequest } from './add-ldap-connection-handler-request';
import { AddLdifConnectionHandlerRequest } from './add-ldif-connection-handler-request';
import { EnumconnectionHandlerSslClientAuthPolicyProp } from './enumconnection-handler-ssl-client-auth-policy-prop';
import { EnumhttpConnectionHandlerSchemaUrn } from './enumhttp-connection-handler-schema-urn';

/**
 * @type AddConnectionHandlerRequest
 * @export
 */
export type AddConnectionHandlerRequest = AddHttpConnectionHandlerRequest | AddJmxConnectionHandlerRequest | AddLdapConnectionHandlerRequest | AddLdifConnectionHandlerRequest;


