/*
PingData Config - OpenAPI 3.0

This is the PingData Configuration API

The version of the OpenAPI document: 0.1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AddBlindTrustManagerProviderRequestAllOf } from './add-blind-trust-manager-provider-request-all-of';
import { EnumfileBasedTrustManagerProviderSchemaUrn } from './enumfile-based-trust-manager-provider-schema-urn';
import { FileBasedTrustManagerProviderShared } from './file-based-trust-manager-provider-shared';

/**
 * @type AddFileBasedTrustManagerProviderRequest
 * @export
 */
export type AddFileBasedTrustManagerProviderRequest = AddBlindTrustManagerProviderRequestAllOf & FileBasedTrustManagerProviderShared;


