/*
PingData Config - OpenAPI 3.0

This is the PingData Configuration API

The version of the OpenAPI document: 0.1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AddArgon2dPasswordStorageSchemeRequestAllOf } from './add-argon2d-password-storage-scheme-request-all-of';
import { Argon2iPasswordStorageSchemeShared } from './argon2i-password-storage-scheme-shared';
import { Enumargon2iPasswordStorageSchemeSchemaUrn } from './enumargon2i-password-storage-scheme-schema-urn';

/**
 * @type AddArgon2iPasswordStorageSchemeRequest
 * @export
 */
export type AddArgon2iPasswordStorageSchemeRequest = AddArgon2dPasswordStorageSchemeRequestAllOf & Argon2iPasswordStorageSchemeShared;


