/*
PingData Config - OpenAPI 3.0

This is the PingData Configuration API

The version of the OpenAPI document: 0.1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AddSubjectEqualsDnCertificateMapperRequestAllOf } from './add-subject-equals-dn-certificate-mapper-request-all-of';
import { EnumsubjectDnToUserAttributeCertificateMapperSchemaUrn } from './enumsubject-dn-to-user-attribute-certificate-mapper-schema-urn';
import { SubjectDnToUserAttributeCertificateMapperShared } from './subject-dn-to-user-attribute-certificate-mapper-shared';

/**
 * @type AddSubjectDnToUserAttributeCertificateMapperRequest
 * @export
 */
export type AddSubjectDnToUserAttributeCertificateMapperRequest = AddSubjectEqualsDnCertificateMapperRequestAllOf & SubjectDnToUserAttributeCertificateMapperShared;


