/*
PingData Config - OpenAPI 3.0

This is the PingData Configuration API

The version of the OpenAPI document: 0.1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AddMirrorVirtualAttributeRequestAllOf } from './add-mirror-virtual-attribute-request-all-of';
import { EnumuserDefinedVirtualAttributeSchemaUrn } from './enumuser-defined-virtual-attribute-schema-urn';
import { EnumvirtualAttributeConflictBehaviorProp } from './enumvirtual-attribute-conflict-behavior-prop';
import { EnumvirtualAttributeMultipleVirtualAttributeMergeBehaviorProp } from './enumvirtual-attribute-multiple-virtual-attribute-merge-behavior-prop';
import { UserDefinedVirtualAttributeShared } from './user-defined-virtual-attribute-shared';

/**
 * @type AddUserDefinedVirtualAttributeRequest
 * @export
 */
export type AddUserDefinedVirtualAttributeRequest = AddMirrorVirtualAttributeRequestAllOf & UserDefinedVirtualAttributeShared;


