/*
PingData Config - OpenAPI 3.0

This is the PingData Configuration API

The version of the OpenAPI document: 0.1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AddEncryptionSettingsDatabaseAccessibilityMonitorProviderRequestAllOf } from './add-encryption-settings-database-accessibility-monitor-provider-request-all-of';
import { EnumthirdPartyMonitorProviderSchemaUrn } from './enumthird-party-monitor-provider-schema-urn';
import { ThirdPartyMonitorProviderShared } from './third-party-monitor-provider-shared';

/**
 * @type AddThirdPartyMonitorProviderRequest
 * @export
 */
export type AddThirdPartyMonitorProviderRequest = AddEncryptionSettingsDatabaseAccessibilityMonitorProviderRequestAllOf & ThirdPartyMonitorProviderShared;


