/*
PingData Config - OpenAPI 3.0

This is the PingData Configuration API

The version of the OpenAPI document: 0.1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AddArgon2dPasswordStorageSchemeRequestAllOf } from './add-argon2d-password-storage-scheme-request-all-of';
import { EnumthirdPartyEnhancedPasswordStorageSchemeSchemaUrn } from './enumthird-party-enhanced-password-storage-scheme-schema-urn';
import { ThirdPartyEnhancedPasswordStorageSchemeShared } from './third-party-enhanced-password-storage-scheme-shared';

/**
 * @type AddThirdPartyEnhancedPasswordStorageSchemeRequest
 * @export
 */
export type AddThirdPartyEnhancedPasswordStorageSchemeRequest = AddArgon2dPasswordStorageSchemeRequestAllOf & ThirdPartyEnhancedPasswordStorageSchemeShared;


