/*
PingData Config - OpenAPI 3.0

This is the PingData Configuration API

The version of the OpenAPI document: 0.1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AddCertificateDelegatedAdminAttributeRequestAllOf } from './add-certificate-delegated-admin-attribute-request-all-of';
import { EnumdelegatedAdminAttributeAttributePresentationProp } from './enumdelegated-admin-attribute-attribute-presentation-prop';
import { EnumdelegatedAdminAttributeMutabilityProp } from './enumdelegated-admin-attribute-mutability-prop';
import { EnumgenericDelegatedAdminAttributeSchemaUrn } from './enumgeneric-delegated-admin-attribute-schema-urn';
import { GenericDelegatedAdminAttributeShared } from './generic-delegated-admin-attribute-shared';

/**
 * @type AddGenericDelegatedAdminAttributeRequest
 * @export
 */
export type AddGenericDelegatedAdminAttributeRequest = AddCertificateDelegatedAdminAttributeRequestAllOf & GenericDelegatedAdminAttributeShared;


