/*
PingData Config - OpenAPI 3.0

This is the PingData Configuration API

The version of the OpenAPI document: 0.1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AddTraditionalStaticGroupSupportForInvertedStaticGroupsPluginRequestAllOf } from './add-traditional-static-group-support-for-inverted-static-groups-plugin-request-all-of';
import { EnumpassThroughAuthenticationPluginSchemaUrn } from './enumpass-through-authentication-plugin-schema-urn';
import { EnumpluginPluginTypeProp } from './enumplugin-plugin-type-prop';
import { EnumpluginServerAccessModeProp } from './enumplugin-server-access-mode-prop';
import { PassThroughAuthenticationPluginShared } from './pass-through-authentication-plugin-shared';

/**
 * @type AddPassThroughAuthenticationPluginRequest
 * @export
 */
export type AddPassThroughAuthenticationPluginRequest = AddTraditionalStaticGroupSupportForInvertedStaticGroupsPluginRequestAllOf & PassThroughAuthenticationPluginShared;


