/*
PingData Config - OpenAPI 3.0

This is the PingData Configuration API

The version of the OpenAPI document: 0.1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AddCharacterSetPasswordValidatorRequestAllOf } from './add-character-set-password-validator-request-all-of';
import { EnumpasswordValidatorMatchBehaviorProp } from './enumpassword-validator-match-behavior-prop';
import { EnumregularExpressionPasswordValidatorSchemaUrn } from './enumregular-expression-password-validator-schema-urn';
import { RegularExpressionPasswordValidatorShared } from './regular-expression-password-validator-shared';

/**
 * @type AddRegularExpressionPasswordValidatorRequest
 * @export
 */
export type AddRegularExpressionPasswordValidatorRequest = AddCharacterSetPasswordValidatorRequestAllOf & RegularExpressionPasswordValidatorShared;


