/*
PingData Config - OpenAPI 3.0

This is the PingData Configuration API

The version of the OpenAPI document: 0.1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { EnumaggregateIdentityMapperSchemaUrn } from './enumaggregate-identity-mapper-schema-urn';

/**
 * 
 * @export
 * @interface AggregateIdentityMapperShared
 */
export interface AggregateIdentityMapperShared {
    /**
     * A description for this Identity Mapper
     * @type {string}
     * @memberof AggregateIdentityMapperShared
     */
    'description'?: string;
    /**
     * 
     * @type {Array<EnumaggregateIdentityMapperSchemaUrn>}
     * @memberof AggregateIdentityMapperShared
     */
    'schemas': Array<EnumaggregateIdentityMapperSchemaUrn>;
    /**
     * The set of identity mappers that must all match the target entry. Each identity mapper must uniquely match the same target entry. If any of the identity mappers match multiple entries, if any of them match zero entries, or if any of them match different entries, then the mapping will fail.
     * @type {Array<string>}
     * @memberof AggregateIdentityMapperShared
     */
    'allIncludedIdentityMapper'?: Array<string>;
    /**
     * The set of identity mappers that will be used to identify the target entry. At least one identity mapper must uniquely match an entry. If multiple identity mappers match entries, then they must all uniquely match the same entry. If none of the identity mappers match any entries, if any of them match multiple entries, or if any of them match different entries, then the mapping will fail.
     * @type {Array<string>}
     * @memberof AggregateIdentityMapperShared
     */
    'anyIncludedIdentityMapper'?: Array<string>;
    /**
     * Indicates whether the Identity Mapper is enabled for use.
     * @type {boolean}
     * @memberof AggregateIdentityMapperShared
     */
    'enabled': boolean;
}

