/*
PingData Config - OpenAPI 3.0

This is the PingData Configuration API

The version of the OpenAPI document: 0.1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { EnumaggregateRequestCriteriaSchemaUrn } from './enumaggregate-request-criteria-schema-urn';

/**
 * 
 * @export
 * @interface AggregateRequestCriteriaShared
 */
export interface AggregateRequestCriteriaShared {
    /**
     * A description for this Request Criteria
     * @type {string}
     * @memberof AggregateRequestCriteriaShared
     */
    'description'?: string;
    /**
     * 
     * @type {Array<EnumaggregateRequestCriteriaSchemaUrn>}
     * @memberof AggregateRequestCriteriaShared
     */
    'schemas': Array<EnumaggregateRequestCriteriaSchemaUrn>;
    /**
     * Specifies a request criteria object that must match the associated operation request in order to match the aggregate request criteria. If one or more all-included request criteria objects are provided, then an operation request must match all of them in order to match the aggregate request criteria.
     * @type {Array<string>}
     * @memberof AggregateRequestCriteriaShared
     */
    'allIncludedRequestCriteria'?: Array<string>;
    /**
     * Specifies a request criteria object that may match the associated operation request in order to the this aggregate request criteria. If one or more any-included request criteria objects are provided, then an operation request must match at least one of them in order to match the aggregate request criteria.
     * @type {Array<string>}
     * @memberof AggregateRequestCriteriaShared
     */
    'anyIncludedRequestCriteria'?: Array<string>;
    /**
     * Specifies a request criteria object that should not match the associated operation request in order to match the aggregate request criteria. If one or more not-all-included request criteria objects are provided, then an operation request must not match all of them (that is, it may match zero or more of them, but it must not match all of them) in order to match the aggregate request criteria.
     * @type {Array<string>}
     * @memberof AggregateRequestCriteriaShared
     */
    'notAllIncludedRequestCriteria'?: Array<string>;
    /**
     * Specifies a request criteria object that must not match the associated operation request in order to match the aggregate request criteria. If one or more none-included request criteria objects are provided, then an operation request must not match any of them in order to match the aggregate request criteria.
     * @type {Array<string>}
     * @memberof AggregateRequestCriteriaShared
     */
    'noneIncludedRequestCriteria'?: Array<string>;
}

