/*
PingData Config - OpenAPI 3.0

This is the PingData Configuration API

The version of the OpenAPI document: 0.1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { EnumalertBackendSchemaUrn } from './enumalert-backend-schema-urn';
import { EnumbackendDisabledAlertTypeProp } from './enumbackend-disabled-alert-type-prop';
import { EnumbackendWritabilityModeProp } from './enumbackend-writability-mode-prop';

/**
 * 
 * @export
 * @interface AlertBackendResponseAllOf
 */
export interface AlertBackendResponseAllOf {
    /**
     * A description for this Backend
     * @type {string}
     * @memberof AlertBackendResponseAllOf
     */
    'description'?: string;
    /**
     * 
     * @type {Array<EnumalertBackendSchemaUrn>}
     * @memberof AlertBackendResponseAllOf
     */
    'schemas'?: Array<EnumalertBackendSchemaUrn>;
    /**
     * Name of the Backend
     * @type {string}
     * @memberof AlertBackendResponseAllOf
     */
    'id'?: string;
    /**
     * Specifies a name to identify the associated backend.
     * @type {string}
     * @memberof AlertBackendResponseAllOf
     */
    'backendID'?: string;
    /**
     * Specifies the base DN(s) for the data that the backend handles.
     * @type {Array<string>}
     * @memberof AlertBackendResponseAllOf
     */
    'baseDN'?: Array<string>;
    /**
     * Specifies the path to the LDIF file that serves as the backing file for this backend.
     * @type {string}
     * @memberof AlertBackendResponseAllOf
     */
    'ldifFile'?: string;
    /**
     * Specifies the maximum length of time that information about generated alerts should be maintained before they will be purged.
     * @type {string}
     * @memberof AlertBackendResponseAllOf
     */
    'alertRetentionTime'?: string;
    /**
     * Specifies the maximum number of alerts that should be retained. If more alerts than this configured maximum are generated within the alert retention time, then the oldest alerts will be purged to achieve this maximum.
     * @type {number}
     * @memberof AlertBackendResponseAllOf
     */
    'maxAlerts'?: number;
    /**
     * 
     * @type {Array<EnumbackendDisabledAlertTypeProp>}
     * @memberof AlertBackendResponseAllOf
     */
    'disabledAlertType'?: Array<EnumbackendDisabledAlertTypeProp>;
    /**
     * Specifies the behavior that the backend should use when processing write operations.
     * @type {EnumbackendWritabilityModeProp}
     * @memberof AlertBackendResponseAllOf
     */
    'writabilityMode'?: EnumbackendWritabilityModeProp;
    /**
     * Indicates whether the backend is enabled in the server.
     * @type {boolean}
     * @memberof AlertBackendResponseAllOf
     */
    'enabled'?: boolean;
    /**
     * Determines whether the Directory Server enters a DEGRADED state (and sends a corresponding alert) when this Backend is disabled.
     * @type {boolean}
     * @memberof AlertBackendResponseAllOf
     */
    'setDegradedAlertWhenDisabled'?: boolean;
    /**
     * Determines whether any LDAP operation that would use this Backend is to return UNAVAILABLE when this Backend is disabled.
     * @type {boolean}
     * @memberof AlertBackendResponseAllOf
     */
    'returnUnavailableWhenDisabled'?: boolean;
    /**
     * Specifies the permissions that should be applied to files and directories created by a backup of the backend.
     * @type {string}
     * @memberof AlertBackendResponseAllOf
     */
    'backupFilePermissions'?: string;
    /**
     * Specifies a notification manager for changes resulting from operations processed through this Backend
     * @type {string}
     * @memberof AlertBackendResponseAllOf
     */
    'notificationManager'?: string;
}

