/*
PingData Config - OpenAPI 3.0

This is the PingData Configuration API

The version of the OpenAPI document: 0.1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { EnumappRoleVaultAuthenticationMethodSchemaUrn } from './enumapp-role-vault-authentication-method-schema-urn';

/**
 * 
 * @export
 * @interface AppRoleVaultAuthenticationMethodShared
 */
export interface AppRoleVaultAuthenticationMethodShared {
    /**
     * A description for this Vault Authentication Method
     * @type {string}
     * @memberof AppRoleVaultAuthenticationMethodShared
     */
    'description'?: string;
    /**
     * 
     * @type {Array<EnumappRoleVaultAuthenticationMethodSchemaUrn>}
     * @memberof AppRoleVaultAuthenticationMethodShared
     */
    'schemas': Array<EnumappRoleVaultAuthenticationMethodSchemaUrn>;
    /**
     * The role ID for the AppRole to authenticate.
     * @type {string}
     * @memberof AppRoleVaultAuthenticationMethodShared
     */
    'vaultRoleID': string;
    /**
     * The secret ID for the AppRole to authenticate.
     * @type {string}
     * @memberof AppRoleVaultAuthenticationMethodShared
     */
    'vaultSecretID': string;
    /**
     * The name used when enabling the desired AppRole authentication mechanism in the Vault server.
     * @type {string}
     * @memberof AppRoleVaultAuthenticationMethodShared
     */
    'loginMechanismName'?: string;
}

