/*
PingData Config - OpenAPI 3.0

This is the PingData Configuration API

The version of the OpenAPI document: 0.1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { EnumapproximateMatchingRuleSchemaUrn } from './enumapproximate-matching-rule-schema-urn';

/**
 * 
 * @export
 * @interface ApproximateMatchingRuleResponseAllOf
 */
export interface ApproximateMatchingRuleResponseAllOf {
    /**
     * 
     * @type {Array<EnumapproximateMatchingRuleSchemaUrn>}
     * @memberof ApproximateMatchingRuleResponseAllOf
     */
    'schemas'?: Array<EnumapproximateMatchingRuleSchemaUrn>;
    /**
     * Name of the Matching Rule
     * @type {string}
     * @memberof ApproximateMatchingRuleResponseAllOf
     */
    'id'?: string;
    /**
     * Indicates whether the Matching Rule is enabled for use.
     * @type {boolean}
     * @memberof ApproximateMatchingRuleResponseAllOf
     */
    'enabled'?: boolean;
}

