/*
PingData Config - OpenAPI 3.0

This is the PingData Configuration API

The version of the OpenAPI document: 0.1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { EnumblindTrustManagerProviderSchemaUrn } from './enumblind-trust-manager-provider-schema-urn';

/**
 * 
 * @export
 * @interface BlindTrustManagerProviderShared
 */
export interface BlindTrustManagerProviderShared {
    /**
     * 
     * @type {Array<EnumblindTrustManagerProviderSchemaUrn>}
     * @memberof BlindTrustManagerProviderShared
     */
    'schemas': Array<EnumblindTrustManagerProviderSchemaUrn>;
    /**
     * Indicate whether the Trust Manager Provider is enabled for use.
     * @type {boolean}
     * @memberof BlindTrustManagerProviderShared
     */
    'enabled': boolean;
    /**
     * Indicates whether certificates issued by an authority included in the JVM\'s set of default issuers should be automatically trusted, even if they would not otherwise be trusted by this provider.
     * @type {boolean}
     * @memberof BlindTrustManagerProviderShared
     */
    'includeJVMDefaultIssuers'?: boolean;
}

