/*
PingData Config - OpenAPI 3.0

This is the PingData Configuration API

The version of the OpenAPI document: 0.1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { EnumcharacterSetPasswordValidatorSchemaUrn } from './enumcharacter-set-password-validator-schema-urn';

/**
 * 
 * @export
 * @interface CharacterSetPasswordValidatorShared
 */
export interface CharacterSetPasswordValidatorShared {
    /**
     * A description for this Password Validator
     * @type {string}
     * @memberof CharacterSetPasswordValidatorShared
     */
    'description'?: string;
    /**
     * 
     * @type {Array<EnumcharacterSetPasswordValidatorSchemaUrn>}
     * @memberof CharacterSetPasswordValidatorShared
     */
    'schemas': Array<EnumcharacterSetPasswordValidatorSchemaUrn>;
    /**
     * Specifies a character set containing characters that a password may contain and a value indicating the minimum number of characters required from that set.
     * @type {Array<string>}
     * @memberof CharacterSetPasswordValidatorShared
     */
    'characterSet': Array<string>;
    /**
     * Indicates whether this password validator allows passwords to contain characters outside of any of the user-defined character sets.
     * @type {boolean}
     * @memberof CharacterSetPasswordValidatorShared
     */
    'allowUnclassifiedCharacters': boolean;
    /**
     * Specifies the minimum number of character sets that must be represented in a proposed password.
     * @type {number}
     * @memberof CharacterSetPasswordValidatorShared
     */
    'minimumRequiredCharacterSets'?: number;
    /**
     * Indicates whether the password validator is enabled for use.
     * @type {boolean}
     * @memberof CharacterSetPasswordValidatorShared
     */
    'enabled': boolean;
    /**
     * Specifies a message that can be used to describe the requirements imposed by this password validator to end users. If a value is provided for this property, then it will override any description that may have otherwise been generated by the validator.
     * @type {string}
     * @memberof CharacterSetPasswordValidatorShared
     */
    'validatorRequirementDescription'?: string;
    /**
     * Specifies a message that may be provided to the end user in the event that a proposed password is rejected by this validator. If a value is provided for this property, then it will override any failure message that may have otherwise been generated by the validator.
     * @type {string}
     * @memberof CharacterSetPasswordValidatorShared
     */
    'validatorFailureMessage'?: string;
}

