/*
PingData Config - OpenAPI 3.0

This is the PingData Configuration API

The version of the OpenAPI document: 0.1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { EnumclientConnectionMonitorProviderSchemaUrn } from './enumclient-connection-monitor-provider-schema-urn';

/**
 * 
 * @export
 * @interface ClientConnectionMonitorProviderResponseAllOf
 */
export interface ClientConnectionMonitorProviderResponseAllOf {
    /**
     * A description for this Monitor Provider
     * @type {string}
     * @memberof ClientConnectionMonitorProviderResponseAllOf
     */
    'description'?: string;
    /**
     * 
     * @type {Array<EnumclientConnectionMonitorProviderSchemaUrn>}
     * @memberof ClientConnectionMonitorProviderResponseAllOf
     */
    'schemas'?: Array<EnumclientConnectionMonitorProviderSchemaUrn>;
    /**
     * Name of the Monitor Provider
     * @type {string}
     * @memberof ClientConnectionMonitorProviderResponseAllOf
     */
    'id'?: string;
    /**
     * Indicates whether the Monitor Provider is enabled for use.
     * @type {boolean}
     * @memberof ClientConnectionMonitorProviderResponseAllOf
     */
    'enabled'?: boolean;
}

