/*
PingData Config - OpenAPI 3.0

This is the PingData Configuration API

The version of the OpenAPI document: 0.1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ConsoleJsonSyncLogPublisherResponseAllOf } from './console-json-sync-log-publisher-response-all-of';
import { EnumconsoleJsonSyncLogPublisherSchemaUrn } from './enumconsole-json-sync-log-publisher-schema-urn';
import { EnumlogPublisherLoggedMessageTypeProp } from './enumlog-publisher-logged-message-type-prop';
import { EnumlogPublisherLoggingErrorBehaviorProp } from './enumlog-publisher-logging-error-behavior-prop';
import { EnumlogPublisherOutputLocationProp } from './enumlog-publisher-output-location-prop';
import { Meta } from './meta';
import { MetaMeta } from './meta-meta';
import { MetaUrnPingidentitySchemasConfigurationMessages20 } from './meta-urn-pingidentity-schemas-configuration-messages20';

/**
 * @type ConsoleJsonSyncLogPublisherResponse
 * @export
 */
export type ConsoleJsonSyncLogPublisherResponse = ConsoleJsonSyncLogPublisherResponseAllOf & Meta;


