/*
PingData Config - OpenAPI 3.0

This is the PingData Configuration API

The version of the OpenAPI document: 0.1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { EnumcustomMonitorProviderSchemaUrn } from './enumcustom-monitor-provider-schema-urn';

/**
 * 
 * @export
 * @interface CustomMonitorProviderResponseAllOf
 */
export interface CustomMonitorProviderResponseAllOf {
    /**
     * A description for this Monitor Provider
     * @type {string}
     * @memberof CustomMonitorProviderResponseAllOf
     */
    'description'?: string;
    /**
     * 
     * @type {Array<EnumcustomMonitorProviderSchemaUrn>}
     * @memberof CustomMonitorProviderResponseAllOf
     */
    'schemas'?: Array<EnumcustomMonitorProviderSchemaUrn>;
    /**
     * Name of the Monitor Provider
     * @type {string}
     * @memberof CustomMonitorProviderResponseAllOf
     */
    'id'?: string;
    /**
     * Indicates whether the Monitor Provider is enabled for use.
     * @type {boolean}
     * @memberof CustomMonitorProviderResponseAllOf
     */
    'enabled'?: boolean;
}

