/*
PingData Config - OpenAPI 3.0

This is the PingData Configuration API

The version of the OpenAPI document: 0.1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface DefaultUncachedAttributeCriteriaResponseAllOf
 */
export interface DefaultUncachedAttributeCriteriaResponseAllOf {
    /**
     * Name of the Uncached Attribute Criteria
     * @type {string}
     * @memberof DefaultUncachedAttributeCriteriaResponseAllOf
     */
    'id'?: string;
}

