/*
PingData Config - OpenAPI 3.0

This is the PingData Configuration API

The version of the OpenAPI document: 0.1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { DefaultUncachedAttributeCriteriaResponseAllOf } from './default-uncached-attribute-criteria-response-all-of';
import { DefaultUncachedAttributeCriteriaShared } from './default-uncached-attribute-criteria-shared';
import { EnumdefaultUncachedAttributeCriteriaSchemaUrn } from './enumdefault-uncached-attribute-criteria-schema-urn';
import { Meta } from './meta';
import { MetaMeta } from './meta-meta';
import { MetaUrnPingidentitySchemasConfigurationMessages20 } from './meta-urn-pingidentity-schemas-configuration-messages20';

/**
 * @type DefaultUncachedAttributeCriteriaResponse
 * @export
 */
export type DefaultUncachedAttributeCriteriaResponse = DefaultUncachedAttributeCriteriaResponseAllOf & DefaultUncachedAttributeCriteriaShared & Meta;


