/*
PingData Config - OpenAPI 3.0

This is the PingData Configuration API

The version of the OpenAPI document: 0.1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { DefaultAzureAuthenticationMethodResponseAllOf } from './default-azure-authentication-method-response-all-of';
import { DefaultAzureAuthenticationMethodShared } from './default-azure-authentication-method-shared';
import { EnumdefaultAzureAuthenticationMethodSchemaUrn } from './enumdefault-azure-authentication-method-schema-urn';
import { Meta } from './meta';
import { MetaMeta } from './meta-meta';
import { MetaUrnPingidentitySchemasConfigurationMessages20 } from './meta-urn-pingidentity-schemas-configuration-messages20';

/**
 * @type DefaultAzureAuthenticationMethodResponse
 * @export
 */
export type DefaultAzureAuthenticationMethodResponse = DefaultAzureAuthenticationMethodResponseAllOf & DefaultAzureAuthenticationMethodShared & Meta;


