/*
PingData Config - OpenAPI 3.0

This is the PingData Configuration API

The version of the OpenAPI document: 0.1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { EnumdynamicGroupImplementationSchemaUrn } from './enumdynamic-group-implementation-schema-urn';

/**
 * 
 * @export
 * @interface DynamicGroupImplementationResponseAllOf
 */
export interface DynamicGroupImplementationResponseAllOf {
    /**
     * A description for this Group Implementation
     * @type {string}
     * @memberof DynamicGroupImplementationResponseAllOf
     */
    'description'?: string;
    /**
     * 
     * @type {Array<EnumdynamicGroupImplementationSchemaUrn>}
     * @memberof DynamicGroupImplementationResponseAllOf
     */
    'schemas'?: Array<EnumdynamicGroupImplementationSchemaUrn>;
    /**
     * Name of the Group Implementation
     * @type {string}
     * @memberof DynamicGroupImplementationResponseAllOf
     */
    'id'?: string;
    /**
     * Indicates whether the Group Implementation is enabled.
     * @type {boolean}
     * @memberof DynamicGroupImplementationResponseAllOf
     */
    'enabled'?: boolean;
}

