/*
PingData Config - OpenAPI 3.0

This is the PingData Configuration API

The version of the OpenAPI document: 0.1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Specifies the circumstances under which the values of the attribute can be written.
 * @export
 * @enum {string}
 */
export type EnumdelegatedAdminAttributeMutabilityProp = 'read-only' | 'read-write'

