/*
PingData Config - OpenAPI 3.0

This is the PingData Configuration API

The version of the OpenAPI document: 0.1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * The mechanism for checking if the hostname of the API External Server matches the name(s) stored inside the server\'s X.509 certificate. This is only applicable if SSL is being used for connection security.
 * @export
 * @enum {string}
 */
export type EnumexternalServerApiHostnameVerificationMethodProp = 'allow-all' | 'strict'

