/*
PingData Config - OpenAPI 3.0

This is the PingData Configuration API

The version of the OpenAPI document: 0.1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Indicates whether users can change their passwords by providing a pre-encoded value.
 * @export
 * @enum {string}
 */
export type EnumpasswordPolicyAllowPreEncodedPasswordsProp = 'false' | 'add-only' | 'admin-reset-only' | 'add-and-admin-reset-only' | 'true'

