/*
PingData Config - OpenAPI 3.0

This is the PingData Configuration API

The version of the OpenAPI document: 0.1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @enum {string}
 */
export type EnumthirdPartyTrustManagerProviderSchemaUrn = 'urn:pingidentity:schemas:configuration:2.0:trust-manager-provider:third-party'

