/*
PingData Config - OpenAPI 3.0

This is the PingData Configuration API

The version of the OpenAPI document: 0.1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Specifies the maximum complexity level for managed configuration elements.
 * @export
 * @enum {string}
 */
export type EnumwebApplicationExtensionComplexityProp = 'basic' | 'standard' | 'advanced' | 'expert'

