/*
PingData Config - OpenAPI 3.0

This is the PingData Configuration API

The version of the OpenAPI document: 0.1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Specifies which operations performed on soft-deleted entries will appear in the changelog.
 * @export
 * @enum {string}
 */
export type EnumbackendSoftDeleteEntryIncludedOperationProp = 'modify' | 'delete'

