/*
PingData Config - OpenAPI 3.0

This is the PingData Configuration API

The version of the OpenAPI document: 0.1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Specifies the kinds of write operations the Directory Server can process.
 * @export
 * @enum {string}
 */
export type EnumglobalConfigurationWritabilityModeProp = 'enabled' | 'disabled' | 'internal-only'

