/*
PingData Config - OpenAPI 3.0

This is the PingData Configuration API

The version of the OpenAPI document: 0.1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * The criteria to use when performing matching based on the assurance timeout.
 * @export
 * @enum {string}
 */
export type EnumresultCriteriaAssuranceTimeoutCriteriaProp = 'any' | 'less-than-or-equal-to' | 'greater-than-or-equal-to'

