/*
PingData Config - OpenAPI 3.0

This is the PingData Configuration API

The version of the OpenAPI document: 0.1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Specifies the cache mode that should be used when accessing the records in the id2children database, which provides a mapping between the entry ID of a particular entry and the entry IDs of all of its immediate children. This index may be used when performing searches with a single-level scope if the search filter cannot be resolved to a small enough candidate list. The size of this database directly depends on the number of entries that have children.
 * @export
 * @enum {string}
 */
export type EnumbackendId2childrenCacheModeProp = 'cache-keys-and-values' | 'cache-keys-only' | 'no-caching' | 'keep-hot' | 'default' | 'make-cold' | 'evict-leaf-immediately' | 'evict-bin-immediately'

