/*
PingData Config - OpenAPI 3.0

This is the PingData Configuration API

The version of the OpenAPI document: 0.1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * The debug message categories to be logged when none of the defined targets match the message.
 * @export
 * @enum {string}
 */
export type EnumlogPublisherDefaultDebugCategoryProp = 'caught' | 'constructor' | 'data' | 'database-access' | 'enter' | 'exit' | 'message' | 'protocol' | 'thrown'

