/*
PingData Config - OpenAPI 3.0

This is the PingData Configuration API

The version of the OpenAPI document: 0.1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * The privacy protocol to use for SNMPv3 if privacy is to be used.
 * @export
 * @enum {string}
 */
export type EnumpluginAgentPrivacyProtocolProp = 'des' | 'des-ede' | 'aes128' | 'aes192' | 'aes256'

