/*
PingData Config - OpenAPI 3.0

This is the PingData Configuration API

The version of the OpenAPI document: 0.1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Indicates whether this Replication Assurance Result Criteria should match operations based on whether the assurance requirements were altered by a control included in the request from the client.
 * @export
 * @enum {string}
 */
export type EnumresultCriteriaAssuranceBehaviorAlteredByControlProp = 'any' | 'true' | 'false'

