/*
PingData Config - OpenAPI 3.0

This is the PingData Configuration API

The version of the OpenAPI document: 0.1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * The mechanism to use to authenticate to the target server.
 * @export
 * @enum {string}
 */
export type EnumexternalServerOpendjAuthenticationMethodProp = 'none' | 'simple' | 'external' | 'inter-server'

