/*
PingData Config - OpenAPI 3.0

This is the PingData Configuration API

The version of the OpenAPI document: 0.1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Specifies the behavior that the Directory Server should exhibit if a client connection attempts to exceed a rate defined in the maximum-connection-operation-rate property. If the configured behavior is one that will reject requested operations, then that behavior will persist until the end of the corresponding interval. The server will resume allowing that client to perform operations when that interval expires, as long as no other operation rate limits have been exceeded.
 * @export
 * @enum {string}
 */
export type EnumclientConnectionPolicyConnectionOperationRateExceededBehaviorProp = 'disconnect' | 'reject-admin-limit-exceeded' | 'reject-constraint-violation' | 'reject-busy' | 'reject-unavailable' | 'reject-unwilling-to-perform' | 'reject-other'

