/*
PingData Config - OpenAPI 3.0

This is the PingData Configuration API

The version of the OpenAPI document: 0.1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * The scope for searches used to identify joined entries.
 * @export
 * @enum {string}
 */
export type EnumvirtualAttributeJoinScopeProp = 'base-object' | 'single-level' | 'whole-subtree' | 'subordinate-subtree'

