/*
PingData Config - OpenAPI 3.0

This is the PingData Configuration API

The version of the OpenAPI document: 0.1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { EnumexactMatchIdentityMapperSchemaUrn } from './enumexact-match-identity-mapper-schema-urn';
import { ExactMatchIdentityMapperResponseAllOf } from './exact-match-identity-mapper-response-all-of';
import { ExactMatchIdentityMapperShared } from './exact-match-identity-mapper-shared';
import { Meta } from './meta';
import { MetaMeta } from './meta-meta';
import { MetaUrnPingidentitySchemasConfigurationMessages20 } from './meta-urn-pingidentity-schemas-configuration-messages20';

/**
 * @type ExactMatchIdentityMapperResponse
 * @export
 */
export type ExactMatchIdentityMapperResponse = ExactMatchIdentityMapperResponseAllOf & ExactMatchIdentityMapperShared & Meta;


