/*
PingData Config - OpenAPI 3.0

This is the PingData Configuration API

The version of the OpenAPI document: 0.1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { EnumexactMatchIdentityMapperSchemaUrn } from './enumexact-match-identity-mapper-schema-urn';

/**
 * 
 * @export
 * @interface ExactMatchIdentityMapperShared
 */
export interface ExactMatchIdentityMapperShared {
    /**
     * A description for this Identity Mapper
     * @type {string}
     * @memberof ExactMatchIdentityMapperShared
     */
    'description'?: string;
    /**
     * 
     * @type {Array<EnumexactMatchIdentityMapperSchemaUrn>}
     * @memberof ExactMatchIdentityMapperShared
     */
    'schemas': Array<EnumexactMatchIdentityMapperSchemaUrn>;
    /**
     * Specifies the attribute whose value should exactly match the ID string provided to this identity mapper.
     * @type {Array<string>}
     * @memberof ExactMatchIdentityMapperShared
     */
    'matchAttribute'?: Array<string>;
    /**
     * Specifies the set of base DNs below which to search for users.
     * @type {Array<string>}
     * @memberof ExactMatchIdentityMapperShared
     */
    'matchBaseDN'?: Array<string>;
    /**
     * An optional filter that mapped users must match.
     * @type {string}
     * @memberof ExactMatchIdentityMapperShared
     */
    'matchFilter'?: string;
    /**
     * Indicates whether the Identity Mapper is enabled for use.
     * @type {boolean}
     * @memberof ExactMatchIdentityMapperShared
     */
    'enabled': boolean;
}

