/*
PingData Config - OpenAPI 3.0

This is the PingData Configuration API

The version of the OpenAPI document: 0.1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { EnumexportReversiblePasswordsExtendedOperationHandlerSchemaUrn } from './enumexport-reversible-passwords-extended-operation-handler-schema-urn';
import { ExportReversiblePasswordsExtendedOperationHandlerShared } from './export-reversible-passwords-extended-operation-handler-shared';
import { Meta } from './meta';
import { MetaMeta } from './meta-meta';
import { MetaUrnPingidentitySchemasConfigurationMessages20 } from './meta-urn-pingidentity-schemas-configuration-messages20';
import { ValidateTotpPasswordExtendedOperationHandlerResponseAllOf } from './validate-totp-password-extended-operation-handler-response-all-of';

/**
 * @type ExportReversiblePasswordsExtendedOperationHandlerResponse
 * @export
 */
export type ExportReversiblePasswordsExtendedOperationHandlerResponse = ExportReversiblePasswordsExtendedOperationHandlerShared & Meta & ValidateTotpPasswordExtendedOperationHandlerResponseAllOf;


