/*
PingData Config - OpenAPI 3.0

This is the PingData Configuration API

The version of the OpenAPI document: 0.1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { EnumgenericRestResourceTypeSchemaUrn } from './enumgeneric-rest-resource-type-schema-urn';
import { GenericRestResourceTypeShared } from './generic-rest-resource-type-shared';
import { Meta } from './meta';
import { MetaMeta } from './meta-meta';
import { MetaUrnPingidentitySchemasConfigurationMessages20 } from './meta-urn-pingidentity-schemas-configuration-messages20';
import { UserRestResourceTypeResponseAllOf } from './user-rest-resource-type-response-all-of';

/**
 * @type GenericRestResourceTypeResponse
 * @export
 */
export type GenericRestResourceTypeResponse = GenericRestResourceTypeShared & Meta & UserRestResourceTypeResponseAllOf;


