/*
PingData Config - OpenAPI 3.0

This is the PingData Configuration API

The version of the OpenAPI document: 0.1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CustomAlertHandlerResponse } from './custom-alert-handler-response';
import { EnumalertHandlerDisabledAlertTypeProp } from './enumalert-handler-disabled-alert-type-prop';
import { EnumalertHandlerEnabledAlertSeverityProp } from './enumalert-handler-enabled-alert-severity-prop';
import { EnumalertHandlerEnabledAlertTypeProp } from './enumalert-handler-enabled-alert-type-prop';
import { EnumalertHandlerLongMessageBehaviorProp } from './enumalert-handler-long-message-behavior-prop';
import { EnumalertHandlerOutputFormatProp } from './enumalert-handler-output-format-prop';
import { EnumalertHandlerOutputLocationProp } from './enumalert-handler-output-location-prop';
import { EnumthirdPartyAlertHandlerSchemaUrn } from './enumthird-party-alert-handler-schema-urn';
import { ErrorLogAlertHandlerResponse } from './error-log-alert-handler-response';
import { ExecAlertHandlerResponse } from './exec-alert-handler-response';
import { GroovyScriptedAlertHandlerResponse } from './groovy-scripted-alert-handler-response';
import { JmxAlertHandlerResponse } from './jmx-alert-handler-response';
import { MetaMeta } from './meta-meta';
import { MetaUrnPingidentitySchemasConfigurationMessages20 } from './meta-urn-pingidentity-schemas-configuration-messages20';
import { OutputAlertHandlerResponse } from './output-alert-handler-response';
import { SmtpAlertHandlerResponse } from './smtp-alert-handler-response';
import { SnmpAlertHandlerResponse } from './snmp-alert-handler-response';
import { SnmpSubAgentAlertHandlerResponse } from './snmp-sub-agent-alert-handler-response';
import { ThirdPartyAlertHandlerResponse } from './third-party-alert-handler-response';
import { TwilioAlertHandlerResponse } from './twilio-alert-handler-response';

/**
 * @type GetAlertHandler200Response
 * @export
 */
export type GetAlertHandler200Response = CustomAlertHandlerResponse | ErrorLogAlertHandlerResponse | ExecAlertHandlerResponse | GroovyScriptedAlertHandlerResponse | JmxAlertHandlerResponse | OutputAlertHandlerResponse | SmtpAlertHandlerResponse | SnmpAlertHandlerResponse | SnmpSubAgentAlertHandlerResponse | ThirdPartyAlertHandlerResponse | TwilioAlertHandlerResponse;


