/*
PingData Config - OpenAPI 3.0

This is the PingData Configuration API

The version of the OpenAPI document: 0.1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { EnumglobalConfigurationAllowedInsecureTLSProtocolProp } from './enumglobal-configuration-allowed-insecure-tlsprotocol-prop';
import { EnumglobalConfigurationAttributesModifiableWithIgnoreNoUserModificationRequestControlProp } from './enumglobal-configuration-attributes-modifiable-with-ignore-no-user-modification-request-control-prop';
import { EnumglobalConfigurationDisabledPrivilegeProp } from './enumglobal-configuration-disabled-privilege-prop';
import { EnumglobalConfigurationInvalidAttributeSyntaxBehaviorProp } from './enumglobal-configuration-invalid-attribute-syntax-behavior-prop';
import { EnumglobalConfigurationJmxValueBehaviorProp } from './enumglobal-configuration-jmx-value-behavior-prop';
import { EnumglobalConfigurationSchemaUrn } from './enumglobal-configuration-schema-urn';
import { EnumglobalConfigurationSingleStructuralObjectclassBehaviorProp } from './enumglobal-configuration-single-structural-objectclass-behavior-prop';
import { EnumglobalConfigurationStartupErrorLoggerOutputLocationProp } from './enumglobal-configuration-startup-error-logger-output-location-prop';
import { EnumglobalConfigurationUnrecoverableDatabaseErrorModeProp } from './enumglobal-configuration-unrecoverable-database-error-mode-prop';
import { EnumglobalConfigurationWritabilityModeProp } from './enumglobal-configuration-writability-mode-prop';

/**
 * 
 * @export
 * @interface GlobalConfigurationResponseAllOf
 */
export interface GlobalConfigurationResponseAllOf {
    /**
     * 
     * @type {Array<EnumglobalConfigurationSchemaUrn>}
     * @memberof GlobalConfigurationResponseAllOf
     */
    'schemas'?: Array<EnumglobalConfigurationSchemaUrn>;
    /**
     * Specifies a name that may be used to uniquely identify this Directory Server instance among other instances in the environment.
     * @type {string}
     * @memberof GlobalConfigurationResponseAllOf
     */
    'instanceName'?: string;
    /**
     * Specifies the location for this Directory Server. Operations performed which involve communication with other servers may prefer servers in the same location to help ensure low-latency responses.
     * @type {string}
     * @memberof GlobalConfigurationResponseAllOf
     */
    'location'?: string;
    /**
     * When this property is set, changes made to this server using the console or dsconfig can be automatically applied to all servers in the specified server group.
     * @type {string}
     * @memberof GlobalConfigurationResponseAllOf
     */
    'configurationServerGroup'?: string;
    /**
     * Indicates whether this server should be forced to assume the master role if no other suitable server is found to act as master or if multiple masters are detected. A master is only needed when changes are made to mirrored data, i.e. data specific to the topology itself and cluster-wide configuration data.
     * @type {boolean}
     * @memberof GlobalConfigurationResponseAllOf
     */
    'forceAsMasterForMirroredData'?: boolean;
    /**
     * Indicates whether the Directory Server should encrypt the data that it stores in all components that support it. This may include certain types of backends (including local DB and large attribute backends), the LDAP changelog, and the replication server database.
     * @type {boolean}
     * @memberof GlobalConfigurationResponseAllOf
     */
    'encryptData'?: boolean;
    /**
     * Specifies the cipher stream provider that should be used to protect the contents of the encryption settings database.
     * @type {string}
     * @memberof GlobalConfigurationResponseAllOf
     */
    'encryptionSettingsCipherStreamProvider'?: string;
    /**
     * Indicates whether the server should encrypt backups by default.
     * @type {boolean}
     * @memberof GlobalConfigurationResponseAllOf
     */
    'encryptBackupsByDefault'?: boolean;
    /**
     * The unique identifier for the encryption settings definition to use to generate the encryption key for encrypted backups by default.
     * @type {string}
     * @memberof GlobalConfigurationResponseAllOf
     */
    'backupEncryptionSettingsDefinitionID'?: string;
    /**
     * Indicates whether the server should encrypt LDIF exports by default.
     * @type {boolean}
     * @memberof GlobalConfigurationResponseAllOf
     */
    'encryptLDIFExportsByDefault'?: boolean;
    /**
     * The unique identifier for the encryption settings definition to use to generate the encryption key for encrypted LDIF exports by default.
     * @type {string}
     * @memberof GlobalConfigurationResponseAllOf
     */
    'ldifExportEncryptionSettingsDefinitionID'?: string;
    /**
     * Indicates whether to automatically compress LDIF exports that are also encrypted.
     * @type {boolean}
     * @memberof GlobalConfigurationResponseAllOf
     */
    'automaticallyCompressEncryptedLDIFExports'?: boolean;
    /**
     * Indicates whether the values of sensitive configuration properties should be redacted when logging configuration changes, including in the configuration audit log, the error log, and the server.out log file.
     * @type {boolean}
     * @memberof GlobalConfigurationResponseAllOf
     */
    'redactSensitiveValuesInConfigLogs'?: boolean;
    /**
     * Provides the ability to indicate that some attributes should be considered sensitive and additional protection should be in place when interacting with those attributes.
     * @type {Array<string>}
     * @memberof GlobalConfigurationResponseAllOf
     */
    'sensitiveAttribute'?: Array<string>;
    /**
     * Indicates whether the Directory Server should reject any LDAP request (other than StartTLS) received from a client that is not using an encrypted connection.
     * @type {boolean}
     * @memberof GlobalConfigurationResponseAllOf
     */
    'rejectInsecureRequests'?: boolean;
    /**
     * A set of criteria that may be used to match LDAP requests that may be permitted over an insecure connection even if reject-insecure-requests is true. Note that some types of requests will always be permitted, including StartTLS and start administrative session requests.
     * @type {string}
     * @memberof GlobalConfigurationResponseAllOf
     */
    'allowedInsecureRequestCriteria'?: string;
    /**
     * Indicates whether the Directory Server should reject any LDAP request (other than bind or StartTLS requests) received from a client that has not yet been authenticated, whose last authentication attempt was unsuccessful, or whose last authentication attempt used anonymous authentication.
     * @type {boolean}
     * @memberof GlobalConfigurationResponseAllOf
     */
    'rejectUnauthenticatedRequests'?: boolean;
    /**
     * A set of criteria that may be used to match LDAP requests that may be permitted over an unauthenticated connection even if reject-unauthenticated-requests is true. Note that some types of requests will always be permitted, including bind, StartTLS, and start administrative session requests.
     * @type {string}
     * @memberof GlobalConfigurationResponseAllOf
     */
    'allowedUnauthenticatedRequestCriteria'?: string;
    /**
     * Indicates whether the Directory Server should reject any simple bind request that contains a DN but no password.
     * @type {boolean}
     * @memberof GlobalConfigurationResponseAllOf
     */
    'bindWithDNRequiresPassword'?: boolean;
    /**
     * 
     * @type {Array<EnumglobalConfigurationDisabledPrivilegeProp>}
     * @memberof GlobalConfigurationResponseAllOf
     */
    'disabledPrivilege'?: Array<EnumglobalConfigurationDisabledPrivilegeProp>;
    /**
     * Specifies the name of the password policy that is in effect for users whose entries do not specify an alternate password policy (either via a real or virtual attribute).
     * @type {string}
     * @memberof GlobalConfigurationResponseAllOf
     */
    'defaultPasswordPolicy'?: string;
    /**
     * Specifies the maximum number of password policies that are defined in the user data (that is, outside of the configuration) that the server should cache in memory for faster access. A value of zero indicates that the server should not cache any user data password policies.
     * @type {number}
     * @memberof GlobalConfigurationResponseAllOf
     */
    'maximumUserDataPasswordPoliciesToCache'?: number;
    /**
     * Specifies the name of the identity mapper to map authorization ID values (using the \"u:\" form) provided in the proxied authorization control to the corresponding user entry.
     * @type {string}
     * @memberof GlobalConfigurationResponseAllOf
     */
    'proxiedAuthorizationIdentityMapper'?: string;
    /**
     * Indicates whether the digest should always be verified whenever an entry containing a digest is decoded. If this is \"true\", then if a digest exists, it will always be verified. Otherwise, the digest will be written when encoding entries but ignored when decoding entries but may still be available for other verification processing.
     * @type {boolean}
     * @memberof GlobalConfigurationResponseAllOf
     */
    'verifyEntryDigests'?: boolean;
    /**
     * 
     * @type {Array<EnumglobalConfigurationAllowedInsecureTLSProtocolProp>}
     * @memberof GlobalConfigurationResponseAllOf
     */
    'allowedInsecureTLSProtocol'?: Array<EnumglobalConfigurationAllowedInsecureTLSProtocolProp>;
    /**
     * Indicates that processes attaching to this server\'s local JVM are allowed to access internal data through JMX without the authentication requirements that remote JMX connections are subject to. Please review and understand the data that this option will expose (such as cn=monitor) to client applications to ensure there are no security concerns.
     * @type {boolean}
     * @memberof GlobalConfigurationResponseAllOf
     */
    'allowInsecureLocalJMXConnections'?: boolean;
    /**
     * Specifies the client connection policy that will be used by default for internal operations.
     * @type {string}
     * @memberof GlobalConfigurationResponseAllOf
     */
    'defaultInternalOperationClientConnectionPolicy'?: string;
    /**
     * Specifies the maximum number of entries that the Directory Server should return to clients by default when processing a search operation.
     * @type {number}
     * @memberof GlobalConfigurationResponseAllOf
     */
    'sizeLimit'?: number;
    /**
     * The size limit value that will apply for connections from unauthenticated clients. If this is not specified, then the value of the size-limit property will be applied for both authenticated and unauthenticated connections.
     * @type {number}
     * @memberof GlobalConfigurationResponseAllOf
     */
    'unauthenticatedSizeLimit'?: number;
    /**
     * Specifies the maximum length of time that the Directory Server should be allowed to spend processing a search operation.
     * @type {string}
     * @memberof GlobalConfigurationResponseAllOf
     */
    'timeLimit'?: string;
    /**
     * The time limit value that will apply for connections from unauthenticated clients. If this is not specified, then the value of the time-limit property will be applied for both authenticated and unauthenticated connections.
     * @type {string}
     * @memberof GlobalConfigurationResponseAllOf
     */
    'unauthenticatedTimeLimit'?: string;
    /**
     * Specifies the maximum length of time that a client connection may remain established since its last completed operation.
     * @type {string}
     * @memberof GlobalConfigurationResponseAllOf
     */
    'idleTimeLimit'?: string;
    /**
     * The idle-time-limit limit value that will apply for connections from unauthenticated clients. If this is not specified, then the value of the idle-time-limit property will be applied for both authenticated and unauthenticated connections.
     * @type {string}
     * @memberof GlobalConfigurationResponseAllOf
     */
    'unauthenticatedIdleTimeLimit'?: string;
    /**
     * Specifies the maximum number of entries that the Directory Server should \"look through\" in the course of processing a search request.
     * @type {number}
     * @memberof GlobalConfigurationResponseAllOf
     */
    'lookthroughLimit'?: number;
    /**
     * The lookthrough limit value that will apply for connections from unauthenticated clients. If this is not specified, then the value of the lookthrough-limit property will be applied for both authenticated and unauthenticated connections.
     * @type {number}
     * @memberof GlobalConfigurationResponseAllOf
     */
    'unauthenticatedLookthroughLimit'?: number;
    /**
     * Specifies the maximum number of entries that may be directly joined with any individual search result entry.
     * @type {number}
     * @memberof GlobalConfigurationResponseAllOf
     */
    'ldapJoinSizeLimit'?: number;
    /**
     * Specifies the maximum number of LDAP client connections which may be established to this Directory Server at the same time.
     * @type {number}
     * @memberof GlobalConfigurationResponseAllOf
     */
    'maximumConcurrentConnections'?: number;
    /**
     * Specifies the maximum number of LDAP client connections originating from the same IP address which may be established to this Directory Server at the same time.
     * @type {number}
     * @memberof GlobalConfigurationResponseAllOf
     */
    'maximumConcurrentConnectionsPerIPAddress'?: number;
    /**
     * Specifies the maximum number of LDAP client connections which may be established to this Directory Server at the same time and authenticated as the same user.
     * @type {number}
     * @memberof GlobalConfigurationResponseAllOf
     */
    'maximumConcurrentConnectionsPerBindDN'?: number;
    /**
     * Specifies the maximum number of unindexed searches that may be in progress in this backend at any given time. Any unindexed searches requested while the maximum number of unindexed searches are already being processed will be rejected. A value of zero indicates that no limit will be enforced.
     * @type {number}
     * @memberof GlobalConfigurationResponseAllOf
     */
    'maximumConcurrentUnindexedSearches'?: number;
    /**
     * Specifies the maximum number of attributes that may be included in an add request. This property does not impose any limit on the number of values that an attribute may have.
     * @type {number}
     * @memberof GlobalConfigurationResponseAllOf
     */
    'maximumAttributesPerAddRequest'?: number;
    /**
     * Specifies the maximum number of modifications that may be included in a modify request. This property does not impose any limit on the number of attribute values that a modification may have.
     * @type {number}
     * @memberof GlobalConfigurationResponseAllOf
     */
    'maximumModificationsPerModifyRequest'?: number;
    /**
     * Indicates whether the server should use a separate background thread for each persistent search.
     * @type {boolean}
     * @memberof GlobalConfigurationResponseAllOf
     */
    'backgroundThreadForEachPersistentSearch'?: boolean;
    /**
     * Indicates whether the Directory Server should allow underscores in attribute names and allow attribute names to begin with numeric digits (both of which are violations of the LDAP standards).
     * @type {boolean}
     * @memberof GlobalConfigurationResponseAllOf
     */
    'allowAttributeNameExceptions'?: boolean;
    /**
     * Specifies how the Directory Server should handle operations whenever an attribute value violates the associated attribute syntax.
     * @type {EnumglobalConfigurationInvalidAttributeSyntaxBehaviorProp}
     * @memberof GlobalConfigurationResponseAllOf
     */
    'invalidAttributeSyntaxBehavior'?: EnumglobalConfigurationInvalidAttributeSyntaxBehaviorProp;
    /**
     * Specifies a set of attribute types for which the server will permit values that do not conform to the associated attribute syntax.
     * @type {Array<string>}
     * @memberof GlobalConfigurationResponseAllOf
     */
    'permitSyntaxViolationsForAttribute'?: Array<string>;
    /**
     * Specifies how the Directory Server should handle operations for an entry does not contain a structural object class, or for an entry that contains multiple structural classes.
     * @type {EnumglobalConfigurationSingleStructuralObjectclassBehaviorProp}
     * @memberof GlobalConfigurationResponseAllOf
     */
    'singleStructuralObjectclassBehavior'?: EnumglobalConfigurationSingleStructuralObjectclassBehaviorProp;
    /**
     * 
     * @type {Array<EnumglobalConfigurationAttributesModifiableWithIgnoreNoUserModificationRequestControlProp>}
     * @memberof GlobalConfigurationResponseAllOf
     */
    'attributesModifiableWithIgnoreNoUserModificationRequestControl'?: Array<EnumglobalConfigurationAttributesModifiableWithIgnoreNoUserModificationRequestControlProp>;
    /**
     * The maximum allowed size that the server.out log file will be allowed to have. If a write would cause the file to exceed this size, then the current file will be rotated out of place and a new empty file will be created and the message written to it.
     * @type {string}
     * @memberof GlobalConfigurationResponseAllOf
     */
    'maximumServerOutLogFileSize'?: string;
    /**
     * The maximum number of server.out log files (including the current active log file) that should be retained. When rotating the log file, if the total number of files exceeds this count, then the oldest file(s) will be removed so that the total number of log files is within this limit.
     * @type {number}
     * @memberof GlobalConfigurationResponseAllOf
     */
    'maximumServerOutLogFileCount'?: number;
    /**
     * Specifies how the server should handle error log messages (which may include errors, warnings, and notices) generated during startup. All of these messages will be written to all configured error loggers, but they may also be written to other locations (like standard output, standard error, or the server.out log file) so that they are displayed on the console when the server is starting.
     * @type {EnumglobalConfigurationStartupErrorLoggerOutputLocationProp}
     * @memberof GlobalConfigurationResponseAllOf
     */
    'startupErrorLoggerOutputLocation'?: EnumglobalConfigurationStartupErrorLoggerOutputLocationProp;
    /**
     * Indicates whether the Directory Server should be shut down if a severe error is raised (e.g., an out of memory error) which may prevent the JVM from continuing to run properly.
     * @type {boolean}
     * @memberof GlobalConfigurationResponseAllOf
     */
    'exitOnJVMError'?: boolean;
    /**
     * Specifies the numeric value of the result code when request processing fails due to an internal server error.
     * @type {number}
     * @memberof GlobalConfigurationResponseAllOf
     */
    'serverErrorResultCode'?: number;
    /**
     * Specifies a result code map that should be used for clients that do not have a map associated with their client connection policy. If the associated client connection policy has a result code map, then that map will be used instead. If no map is associated either with the client connection policy or the global configuration, then an internal default will be used.
     * @type {string}
     * @memberof GlobalConfigurationResponseAllOf
     */
    'resultCodeMap'?: string;
    /**
     * Indicates whether responses for failed bind operations should include a message string providing the reason for the authentication failure.
     * @type {boolean}
     * @memberof GlobalConfigurationResponseAllOf
     */
    'returnBindErrorMessages'?: boolean;
    /**
     * Indicates whether the Directory Server should send a response to any operation that is interrupted via an abandon request.
     * @type {boolean}
     * @memberof GlobalConfigurationResponseAllOf
     */
    'notifyAbandonedOperations'?: boolean;
    /**
     * Specifies the maximum number of duplicate error log messages that should be logged in the time window specified by the duplicate-error-log-time-limit property.
     * @type {number}
     * @memberof GlobalConfigurationResponseAllOf
     */
    'duplicateErrorLogLimit'?: number;
    /**
     * Specifies the length of time that must expire before duplicate log messages above the duplicate-error-log-limit threshold are logged again to the error log.
     * @type {string}
     * @memberof GlobalConfigurationResponseAllOf
     */
    'duplicateErrorLogTimeLimit'?: string;
    /**
     * Specifies the maximum number of duplicate alert messages that should be sent via the administrative alert framework in the time window specified by the duplicate-alert-time-limit property.
     * @type {number}
     * @memberof GlobalConfigurationResponseAllOf
     */
    'duplicateAlertLimit'?: number;
    /**
     * Specifies the length of time that must expire before duplicate messages are sent via the administrative alert framework.
     * @type {string}
     * @memberof GlobalConfigurationResponseAllOf
     */
    'duplicateAlertTimeLimit'?: string;
    /**
     * Specifies the kinds of write operations the Directory Server can process.
     * @type {EnumglobalConfigurationWritabilityModeProp}
     * @memberof GlobalConfigurationResponseAllOf
     */
    'writabilityMode'?: EnumglobalConfigurationWritabilityModeProp;
    /**
     * Indicates whether the server should use a common database cache that is shared across all local DB backends instead of maintaining a separate cache for each backend.
     * @type {boolean}
     * @memberof GlobalConfigurationResponseAllOf
     */
    'useSharedDatabaseCacheAcrossAllLocalDBBackends'?: boolean;
    /**
     * Specifies the percentage of the JVM memory to allocate to the database cache that is shared across all local DB backends.
     * @type {number}
     * @memberof GlobalConfigurationResponseAllOf
     */
    'sharedLocalDBBackendDatabaseCachePercent'?: number;
    /**
     * Specifies the action which should be taken for any database that experiences an unrecoverable error. Action applies to local database backends and the replication recent changes database.
     * @type {EnumglobalConfigurationUnrecoverableDatabaseErrorModeProp}
     * @memberof GlobalConfigurationResponseAllOf
     */
    'unrecoverableDatabaseErrorMode'?: EnumglobalConfigurationUnrecoverableDatabaseErrorModeProp;
    /**
     * This setting provides data integrity options when the Directory Server is installed with a database on a network storage device. A storage device may be accessed directly by a physical server, or indirectly through a virtual machine running on a hypervisor. Enabling this setting will apply changes to all Local DB Backends, the LDAP Changelog Backend, and the replication changelog database.
     * @type {boolean}
     * @memberof GlobalConfigurationResponseAllOf
     */
    'databaseOnVirtualizedOrNetworkStorage'?: boolean;
    /**
     * Connection criteria that may be used to identify clients whose add requests should use entryUUID as the naming attribute.
     * @type {string}
     * @memberof GlobalConfigurationResponseAllOf
     */
    'autoNameWithEntryUUIDConnectionCriteria'?: string;
    /**
     * Request criteria that may be used to identify add requests that should use entryUUID as the naming attribute.
     * @type {string}
     * @memberof GlobalConfigurationResponseAllOf
     */
    'autoNameWithEntryUUIDRequestCriteria'?: string;
    /**
     * Specifies the soft delete policy that will be used by default for delete operations. Soft delete operations introduce the ability to control the server behavior of the delete operation. Instead of performing a permanent delete of an entry, deleted entries can be retained as soft deleted entries by their entryUUID values and are available for undelete at a later time. In addition to a soft delete policy enabling soft deletes, delete operations sent to the server must have the soft delete request control present with sufficient access privileges to access the soft delete request control.
     * @type {string}
     * @memberof GlobalConfigurationResponseAllOf
     */
    'softDeletePolicy'?: string;
    /**
     * Specifies the length of time that a subtree may remain hidden or read-only before an administrative alert is sent.
     * @type {string}
     * @memberof GlobalConfigurationResponseAllOf
     */
    'subtreeAccessibilityAlertTimeLimit'?: string;
    /**
     * Indicates whether the server should issue a warning when enabling a backend that contains multiple base DNs.
     * @type {boolean}
     * @memberof GlobalConfigurationResponseAllOf
     */
    'warnForBackendsWithMultipleBaseDns'?: boolean;
    /**
     * Specifies the minimum length of time required for backend or request processor initialization that will trigger the server to force an explicit garbage collection. A value of \"0 seconds\" indicates that the server should never invoke an explicit garbage collection regardless of the length of time required to initialize the server backends.
     * @type {string}
     * @memberof GlobalConfigurationResponseAllOf
     */
    'forcedGCPrimeDuration'?: string;
    /**
     * The name of the replication set assigned to this Directory Server. Restricted domains are only replicated within instances using the same replication set name.
     * @type {string}
     * @memberof GlobalConfigurationResponseAllOf
     */
    'replicationSetName'?: string;
    /**
     * The number of outstanding changes any replica can have before the Directory Server will start accepting connections. The Directory Server may never accept connections if this setting is too low. If you are unsure which value to use, you can use the number of expected updates within a five second interval.
     * @type {number}
     * @memberof GlobalConfigurationResponseAllOf
     */
    'startupMinReplicationBacklogCount'?: number;
    /**
     * An alert is sent when the number of outstanding replication changes for the Directory Server has exceeded this threshold for longer than the replication backlog duration alert threshold.
     * @type {number}
     * @memberof GlobalConfigurationResponseAllOf
     */
    'replicationBacklogCountAlertThreshold'?: number;
    /**
     * An alert is sent when the number of outstanding replication changes for the Directory Server has exceeded the replication backlog count alert threshold for longer than this duration.
     * @type {string}
     * @memberof GlobalConfigurationResponseAllOf
     */
    'replicationBacklogDurationAlertThreshold'?: string;
    /**
     * The amount of time a replication assurance source (i.e. a peer Directory Server) will be suspended from assurance requirements on this Directory Server if it experiences an assurance timeout.
     * @type {string}
     * @memberof GlobalConfigurationResponseAllOf
     */
    'replicationAssuranceSourceTimeoutSuspendDuration'?: string;
    /**
     * The maximum number of replication backlog updates a replication assurance source (i.e. a peer Directory Server) can have and be immediately recognized as an available assurance source by this Directory Server.
     * @type {number}
     * @memberof GlobalConfigurationResponseAllOf
     */
    'replicationAssuranceSourceBacklogFastStartThreshold'?: number;
    /**
     * Specifies the size limit for historical information.
     * @type {number}
     * @memberof GlobalConfigurationResponseAllOf
     */
    'replicationHistoryLimit'?: number;
    /**
     * Allow replication to be inherited by subordinate/child backends.
     * @type {boolean}
     * @memberof GlobalConfigurationResponseAllOf
     */
    'allowInheritedReplicationOfSubordinateBackends'?: boolean;
    /**
     * Indicates whether state about obsolete replicas is automatically purged.
     * @type {boolean}
     * @memberof GlobalConfigurationResponseAllOf
     */
    'replicationPurgeObsoleteReplicas'?: boolean;
    /**
     * Specifies the set of servers that will be used to send email messages. The order in which the servers are listed indicates the order in which the Directory Server will attempt to use them in the course of sending a message. The first attempt will always go to the server at the top of the list, and servers further down the list will only be used if none of the servers listed above it were able to successfully send the message.
     * @type {Array<string>}
     * @memberof GlobalConfigurationResponseAllOf
     */
    'smtpServer'?: Array<string>;
    /**
     * The maximum number of SMTP connections that will be maintained for delivering email messages.
     * @type {number}
     * @memberof GlobalConfigurationResponseAllOf
     */
    'maxSMTPConnectionCount'?: number;
    /**
     * The maximum length of time that a connection to an SMTP server should be considered valid.
     * @type {string}
     * @memberof GlobalConfigurationResponseAllOf
     */
    'maxSMTPConnectionAge'?: string;
    /**
     * The length of time between checks to ensure that available SMTP connections are still valid.
     * @type {string}
     * @memberof GlobalConfigurationResponseAllOf
     */
    'smtpConnectionHealthCheckInterval'?: string;
    /**
     * Specifies the fully-qualified name of a Java class that may be invoked in the server.
     * @type {Array<string>}
     * @memberof GlobalConfigurationResponseAllOf
     */
    'allowedTask'?: Array<string>;
    /**
     * Indicates whether the Directory Server should attempt to record information about the length of time required to process various phases of an operation. Enabling this feature may impact performance, but could make it easier to identify potential bottlenecks in operation processing.
     * @type {boolean}
     * @memberof GlobalConfigurationResponseAllOf
     */
    'enableSubOperationTimer'?: boolean;
    /**
     * Specifies the maximum amount of time the shutdown of Directory Server may take.
     * @type {string}
     * @memberof GlobalConfigurationResponseAllOf
     */
    'maximumShutdownTime'?: string;
    /**
     * Specifies the length of time that the Directory Server should cache the IP addresses associated with the names of systems with which it interacts.
     * @type {string}
     * @memberof GlobalConfigurationResponseAllOf
     */
    'networkAddressCacheTTL'?: string;
    /**
     * Specifies whether the Directory Server should cache the last valid IP addresses associated with the names of systems with which it interacts with when the domain name service returns an unknown host exception. Java may return an unknown host exception when there is unexpected interruption in domain name service so this setting protects the Directory Server from temporary DNS server outages if previous results have been cached.
     * @type {boolean}
     * @memberof GlobalConfigurationResponseAllOf
     */
    'networkAddressOutageCacheEnabled'?: boolean;
    /**
     * Specifies criteria for identifying specific applications that access the server to enable tracking throughput and latency of LDAP operations issued by an application.
     * @type {Array<string>}
     * @memberof GlobalConfigurationResponseAllOf
     */
    'trackedApplication'?: Array<string>;
    /**
     * Specifies how a Java type is chosen for monitor attributes exposed as JMX attribute values.
     * @type {EnumglobalConfigurationJmxValueBehaviorProp}
     * @memberof GlobalConfigurationResponseAllOf
     */
    'jmxValueBehavior'?: EnumglobalConfigurationJmxValueBehaviorProp;
    /**
     * When set to true, the server will use its original, non-standard JMX MBean names for the monitoring MBeans. These include RDN keys of \"Rdn1\" and \"Rdn2\" instead of the recommended \"type\" and \"name\" keys. This should option should only be enabled for installations that have monitoring infrastructure that depends on the old keys.
     * @type {boolean}
     * @memberof GlobalConfigurationResponseAllOf
     */
    'jmxUseLegacyMbeanNames'?: boolean;
}

