/*
PingData Config - OpenAPI 3.0

This is the PingData Configuration API

The version of the OpenAPI document: 0.1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { EnumgssapiSaslMechanismHandlerSchemaUrn } from './enumgssapi-sasl-mechanism-handler-schema-urn';
import { EnumsaslMechanismHandlerAllowedQualityOfProtectionProp } from './enumsasl-mechanism-handler-allowed-quality-of-protection-prop';
import { EnumsaslMechanismHandlerGssapiRoleProp } from './enumsasl-mechanism-handler-gssapi-role-prop';

/**
 * 
 * @export
 * @interface GssapiSaslMechanismHandlerResponseAllOf
 */
export interface GssapiSaslMechanismHandlerResponseAllOf {
    /**
     * A description for this SASL Mechanism Handler
     * @type {string}
     * @memberof GssapiSaslMechanismHandlerResponseAllOf
     */
    'description'?: string;
    /**
     * 
     * @type {Array<EnumgssapiSaslMechanismHandlerSchemaUrn>}
     * @memberof GssapiSaslMechanismHandlerResponseAllOf
     */
    'schemas'?: Array<EnumgssapiSaslMechanismHandlerSchemaUrn>;
    /**
     * Name of the SASL Mechanism Handler
     * @type {string}
     * @memberof GssapiSaslMechanismHandlerResponseAllOf
     */
    'id'?: string;
    /**
     * Specifies the realm to be used for GSSAPI authentication.
     * @type {string}
     * @memberof GssapiSaslMechanismHandlerResponseAllOf
     */
    'realm'?: string;
    /**
     * Specifies the address of the KDC that is to be used for Kerberos processing.
     * @type {string}
     * @memberof GssapiSaslMechanismHandlerResponseAllOf
     */
    'kdcAddress'?: string;
    /**
     * Specifies the keytab file that should be used for Kerberos processing.
     * @type {string}
     * @memberof GssapiSaslMechanismHandlerResponseAllOf
     */
    'keytab'?: string;
    /**
     * Specifies whether or not to allow a null value for the server-fqdn.
     * @type {boolean}
     * @memberof GssapiSaslMechanismHandlerResponseAllOf
     */
    'allowNullServerFqdn'?: boolean;
    /**
     * Specifies the DNS-resolvable fully-qualified domain name for the system.
     * @type {string}
     * @memberof GssapiSaslMechanismHandlerResponseAllOf
     */
    'serverFqdn'?: string;
    /**
     * 
     * @type {Array<EnumsaslMechanismHandlerAllowedQualityOfProtectionProp>}
     * @memberof GssapiSaslMechanismHandlerResponseAllOf
     */
    'allowedQualityOfProtection'?: Array<EnumsaslMechanismHandlerAllowedQualityOfProtectionProp>;
    /**
     * Specifies the name of the identity mapper that is to be used with this SASL mechanism handler to match the Kerberos principal included in the SASL bind request to the corresponding user in the directory.
     * @type {string}
     * @memberof GssapiSaslMechanismHandlerResponseAllOf
     */
    'identityMapper'?: string;
    /**
     * Specifies the name of the identity mapper that is to be used with this SASL mechanism handler to map the alternate authorization identity (if provided, and if different from the Kerberos principal used as the authentication identity) to the corresponding user in the directory. If no value is specified, then the mapper specified in the identity-mapper configuration property will be used.
     * @type {string}
     * @memberof GssapiSaslMechanismHandlerResponseAllOf
     */
    'alternateAuthorizationIdentityMapper'?: string;
    /**
     * Specifies the Kerberos service principal that the Directory Server will use to identify itself to the KDC.
     * @type {string}
     * @memberof GssapiSaslMechanismHandlerResponseAllOf
     */
    'kerberosServicePrincipal'?: string;
    /**
     * Specifies the role that should be declared for the server in the generated JAAS configuration file.
     * @type {EnumsaslMechanismHandlerGssapiRoleProp}
     * @memberof GssapiSaslMechanismHandlerResponseAllOf
     */
    'gssapiRole'?: EnumsaslMechanismHandlerGssapiRoleProp;
    /**
     * Specifies the path to a JAAS (Java Authentication and Authorization Service) configuration file that provides the information that the JVM should use for Kerberos processing.
     * @type {string}
     * @memberof GssapiSaslMechanismHandlerResponseAllOf
     */
    'jaasConfigFile'?: string;
    /**
     * Indicates whether to enable debugging for the Java GSSAPI provider. Debug information will be written to standard output, which should be captured in the server.out log file.
     * @type {boolean}
     * @memberof GssapiSaslMechanismHandlerResponseAllOf
     */
    'enableDebug'?: boolean;
    /**
     * Indicates whether the SASL mechanism handler is enabled for use.
     * @type {boolean}
     * @memberof GssapiSaslMechanismHandlerResponseAllOf
     */
    'enabled'?: boolean;
}

