/*
PingData Config - OpenAPI 3.0

This is the PingData Configuration API

The version of the OpenAPI document: 0.1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { EnumhaystackPasswordValidatorSchemaUrn } from './enumhaystack-password-validator-schema-urn';

/**
 * 
 * @export
 * @interface HaystackPasswordValidatorShared
 */
export interface HaystackPasswordValidatorShared {
    /**
     * A description for this Password Validator
     * @type {string}
     * @memberof HaystackPasswordValidatorShared
     */
    'description'?: string;
    /**
     * 
     * @type {Array<EnumhaystackPasswordValidatorSchemaUrn>}
     * @memberof HaystackPasswordValidatorShared
     */
    'schemas': Array<EnumhaystackPasswordValidatorSchemaUrn>;
    /**
     * The number of password guesses per second that a potential attacker may be expected to make.
     * @type {string}
     * @memberof HaystackPasswordValidatorShared
     */
    'assumedPasswordGuessesPerSecond'?: string;
    /**
     * The minimum length of time (using the configured number of password guesses per second) required to exhaust the entire search space for a proposed password in order for that password to be considered acceptable.
     * @type {string}
     * @memberof HaystackPasswordValidatorShared
     */
    'minimumAcceptableTimeToExhaustSearchSpace'?: string;
    /**
     * Indicates whether the password validator is enabled for use.
     * @type {boolean}
     * @memberof HaystackPasswordValidatorShared
     */
    'enabled': boolean;
    /**
     * Specifies a message that can be used to describe the requirements imposed by this password validator to end users. If a value is provided for this property, then it will override any description that may have otherwise been generated by the validator.
     * @type {string}
     * @memberof HaystackPasswordValidatorShared
     */
    'validatorRequirementDescription'?: string;
    /**
     * Specifies a message that may be provided to the end user in the event that a proposed password is rejected by this validator. If a value is provided for this property, then it will override any failure message that may have otherwise been generated by the validator.
     * @type {string}
     * @memberof HaystackPasswordValidatorShared
     */
    'validatorFailureMessage'?: string;
}

