/*
PingData Config - OpenAPI 3.0

This is the PingData Configuration API

The version of the OpenAPI document: 0.1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { EnumhexStringAttributeSyntaxSchemaUrn } from './enumhex-string-attribute-syntax-schema-urn';

/**
 * 
 * @export
 * @interface HexStringAttributeSyntaxResponseAllOf
 */
export interface HexStringAttributeSyntaxResponseAllOf {
    /**
     * 
     * @type {Array<EnumhexStringAttributeSyntaxSchemaUrn>}
     * @memberof HexStringAttributeSyntaxResponseAllOf
     */
    'schemas'?: Array<EnumhexStringAttributeSyntaxSchemaUrn>;
    /**
     * Name of the Attribute Syntax
     * @type {string}
     * @memberof HexStringAttributeSyntaxResponseAllOf
     */
    'id'?: string;
    /**
     * Indicates whether the Attribute Syntax is enabled.
     * @type {boolean}
     * @memberof HexStringAttributeSyntaxResponseAllOf
     */
    'enabled'?: boolean;
    /**
     * Indicates whether values of this attribute are required to have a \"binary\" transfer option as described in RFC 4522. Attributes with this syntax will generally be referenced with names including \";binary\" (e.g., \"userCertificate;binary\").
     * @type {boolean}
     * @memberof HexStringAttributeSyntaxResponseAllOf
     */
    'requireBinaryTransfer'?: boolean;
}

