/*
PingData Config - OpenAPI 3.0

This is the PingData Configuration API

The version of the OpenAPI document: 0.1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { HttpServletCrossOriginPolicyResponse } from './http-servlet-cross-origin-policy-response';

/**
 * 
 * @export
 * @interface HttpServletCrossOriginPolicyListResponse
 */
export interface HttpServletCrossOriginPolicyListResponse {
    /**
     * 
     * @type {Array<string>}
     * @memberof HttpServletCrossOriginPolicyListResponse
     */
    'schemas'?: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof HttpServletCrossOriginPolicyListResponse
     */
    'totalResults'?: number;
    /**
     * 
     * @type {Array<HttpServletCrossOriginPolicyResponse>}
     * @memberof HttpServletCrossOriginPolicyListResponse
     */
    'Resources'?: Array<HttpServletCrossOriginPolicyResponse>;
}

