/*
PingData Config - OpenAPI 3.0

This is the PingData Configuration API

The version of the OpenAPI document: 0.1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { EnumhttpServerInstanceListenerSchemaUrn } from './enumhttp-server-instance-listener-schema-urn';
import { EnumserverInstanceListenerHttpConnectionSecurityProp } from './enumserver-instance-listener-http-connection-security-prop';
import { EnumserverInstanceListenerPurposeProp } from './enumserver-instance-listener-purpose-prop';

/**
 * 
 * @export
 * @interface HttpServerInstanceListenerResponseAllOf
 */
export interface HttpServerInstanceListenerResponseAllOf {
    /**
     * 
     * @type {Array<EnumhttpServerInstanceListenerSchemaUrn>}
     * @memberof HttpServerInstanceListenerResponseAllOf
     */
    'schemas'?: Array<EnumhttpServerInstanceListenerSchemaUrn>;
    /**
     * Name of the Server Instance Listener
     * @type {string}
     * @memberof HttpServerInstanceListenerResponseAllOf
     */
    'id'?: string;
    /**
     * If the server is listening on a particular address different from the hostname, then this property may be used to specify the address on which to listen for connections from HTTP clients.
     * @type {string}
     * @memberof HttpServerInstanceListenerResponseAllOf
     */
    'listenAddress'?: string;
    /**
     * The TCP port number on which the HTTP server is listening.
     * @type {number}
     * @memberof HttpServerInstanceListenerResponseAllOf
     */
    'serverHTTPPort'?: number;
    /**
     * Specifies the mechanism to use for securing connections to the server.
     * @type {EnumserverInstanceListenerHttpConnectionSecurityProp}
     * @memberof HttpServerInstanceListenerResponseAllOf
     */
    'connectionSecurity'?: EnumserverInstanceListenerHttpConnectionSecurityProp;
    /**
     * 
     * @type {Array<EnumserverInstanceListenerPurposeProp>}
     * @memberof HttpServerInstanceListenerResponseAllOf
     */
    'purpose'?: Array<EnumserverInstanceListenerPurposeProp>;
}

