/*
PingData Config - OpenAPI 3.0

This is the PingData Configuration API

The version of the OpenAPI document: 0.1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { EnumindicatorGaugeDataSourceSchemaUrn } from './enumindicator-gauge-data-source-schema-urn';

/**
 * 
 * @export
 * @interface IndicatorGaugeDataSourceShared
 */
export interface IndicatorGaugeDataSourceShared {
    /**
     * A description for this Gauge Data Source
     * @type {string}
     * @memberof IndicatorGaugeDataSourceShared
     */
    'description'?: string;
    /**
     * 
     * @type {Array<EnumindicatorGaugeDataSourceSchemaUrn>}
     * @memberof IndicatorGaugeDataSourceShared
     */
    'schemas': Array<EnumindicatorGaugeDataSourceSchemaUrn>;
    /**
     * Additional information about the source of this data that is added to alerts sent as a result of gauges that use this Gauge Data Source.
     * @type {string}
     * @memberof IndicatorGaugeDataSourceShared
     */
    'additionalText'?: string;
    /**
     * The object class name of the monitor entries to examine for generating gauge data.
     * @type {string}
     * @memberof IndicatorGaugeDataSourceShared
     */
    'monitorObjectclass': string;
    /**
     * Specifies the attribute on the monitor entries from which to derive the current gauge value.
     * @type {string}
     * @memberof IndicatorGaugeDataSourceShared
     */
    'monitorAttribute': string;
    /**
     * An optional LDAP filter that can be used restrict which monitor entries are used to compute output.
     * @type {string}
     * @memberof IndicatorGaugeDataSourceShared
     */
    'includeFilter'?: string;
    /**
     * Specifies the attribute whose value is used to identify the specific resource being monitored (e.g. device name).
     * @type {string}
     * @memberof IndicatorGaugeDataSourceShared
     */
    'resourceAttribute'?: string;
    /**
     * A string indicating the type of resource being monitored.
     * @type {string}
     * @memberof IndicatorGaugeDataSourceShared
     */
    'resourceType'?: string;
    /**
     * The minimum frequency with which gauges using this Gauge Data Source can be configured for update. In order to prevent undesirable side effects, some Gauge Data Sources may use this property to impose a higher bound on the update frequency of gauges.
     * @type {string}
     * @memberof IndicatorGaugeDataSourceShared
     */
    'minimumUpdateInterval'?: string;
}

