/*
PingData Config - OpenAPI 3.0

This is the PingData Configuration API

The version of the OpenAPI document: 0.1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { EnuminvertedStaticGroupImplementationSchemaUrn } from './enuminverted-static-group-implementation-schema-urn';

/**
 * 
 * @export
 * @interface InvertedStaticGroupImplementationResponseAllOf
 */
export interface InvertedStaticGroupImplementationResponseAllOf {
    /**
     * A description for this Group Implementation
     * @type {string}
     * @memberof InvertedStaticGroupImplementationResponseAllOf
     */
    'description'?: string;
    /**
     * 
     * @type {Array<EnuminvertedStaticGroupImplementationSchemaUrn>}
     * @memberof InvertedStaticGroupImplementationResponseAllOf
     */
    'schemas'?: Array<EnuminvertedStaticGroupImplementationSchemaUrn>;
    /**
     * Name of the Group Implementation
     * @type {string}
     * @memberof InvertedStaticGroupImplementationResponseAllOf
     */
    'id'?: string;
    /**
     * Indicates whether the Group Implementation is enabled.
     * @type {boolean}
     * @memberof InvertedStaticGroupImplementationResponseAllOf
     */
    'enabled'?: boolean;
}

