/*
PingData Config - OpenAPI 3.0

This is the PingData Configuration API

The version of the OpenAPI document: 0.1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { EnuminvertedStaticGroupImplementationSchemaUrn } from './enuminverted-static-group-implementation-schema-urn';
import { InvertedStaticGroupImplementationResponseAllOf } from './inverted-static-group-implementation-response-all-of';
import { Meta } from './meta';
import { MetaMeta } from './meta-meta';
import { MetaUrnPingidentitySchemasConfigurationMessages20 } from './meta-urn-pingidentity-schemas-configuration-messages20';

/**
 * @type InvertedStaticGroupImplementationResponse
 * @export
 */
export type InvertedStaticGroupImplementationResponse = InvertedStaticGroupImplementationResponseAllOf & Meta;


