/*
PingData Config - OpenAPI 3.0

This is the PingData Configuration API

The version of the OpenAPI document: 0.1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { EnumalertHandlerDisabledAlertTypeProp } from './enumalert-handler-disabled-alert-type-prop';
import { EnumalertHandlerEnabledAlertSeverityProp } from './enumalert-handler-enabled-alert-severity-prop';
import { EnumalertHandlerEnabledAlertTypeProp } from './enumalert-handler-enabled-alert-type-prop';
import { EnumjmxAlertHandlerSchemaUrn } from './enumjmx-alert-handler-schema-urn';
import { JmxAlertHandlerShared } from './jmx-alert-handler-shared';
import { Meta } from './meta';
import { MetaMeta } from './meta-meta';
import { MetaUrnPingidentitySchemasConfigurationMessages20 } from './meta-urn-pingidentity-schemas-configuration-messages20';
import { SmtpAlertHandlerResponseAllOf } from './smtp-alert-handler-response-all-of';

/**
 * @type JmxAlertHandlerResponse
 * @export
 */
export type JmxAlertHandlerResponse = JmxAlertHandlerShared & Meta & SmtpAlertHandlerResponseAllOf;


