/*
PingData Config - OpenAPI 3.0

This is the PingData Configuration API

The version of the OpenAPI document: 0.1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { BlindTrustManagerProviderResponseAllOf } from './blind-trust-manager-provider-response-all-of';
import { EnumjvmDefaultTrustManagerProviderSchemaUrn } from './enumjvm-default-trust-manager-provider-schema-urn';
import { JvmDefaultTrustManagerProviderShared } from './jvm-default-trust-manager-provider-shared';
import { Meta } from './meta';
import { MetaMeta } from './meta-meta';
import { MetaUrnPingidentitySchemasConfigurationMessages20 } from './meta-urn-pingidentity-schemas-configuration-messages20';

/**
 * @type JvmDefaultTrustManagerProviderResponse
 * @export
 */
export type JvmDefaultTrustManagerProviderResponse = BlindTrustManagerProviderResponseAllOf & JvmDefaultTrustManagerProviderShared & Meta;


