/*
PingData Config - OpenAPI 3.0

This is the PingData Configuration API

The version of the OpenAPI document: 0.1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { EnumldapServerInstanceListenerSchemaUrn } from './enumldap-server-instance-listener-schema-urn';
import { EnumserverInstanceListenerLdapConnectionSecurityProp } from './enumserver-instance-listener-ldap-connection-security-prop';
import { EnumserverInstanceListenerPurposeProp } from './enumserver-instance-listener-purpose-prop';
import { LdapServerInstanceListenerResponseAllOf } from './ldap-server-instance-listener-response-all-of';
import { Meta } from './meta';
import { MetaMeta } from './meta-meta';
import { MetaUrnPingidentitySchemasConfigurationMessages20 } from './meta-urn-pingidentity-schemas-configuration-messages20';

/**
 * @type LdapServerInstanceListenerResponse
 * @export
 */
export type LdapServerInstanceListenerResponse = LdapServerInstanceListenerResponseAllOf & Meta;


