/*
PingData Config - OpenAPI 3.0

This is the PingData Configuration API

The version of the OpenAPI document: 0.1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { LocalDbIndexResponse } from './local-db-index-response';

/**
 * 
 * @export
 * @interface LocalDbIndexListResponse
 */
export interface LocalDbIndexListResponse {
    /**
     * 
     * @type {Array<string>}
     * @memberof LocalDbIndexListResponse
     */
    'schemas'?: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof LocalDbIndexListResponse
     */
    'totalResults'?: number;
    /**
     * 
     * @type {Array<LocalDbIndexResponse>}
     * @memberof LocalDbIndexListResponse
     */
    'Resources'?: Array<LocalDbIndexResponse>;
}

