/*
PingData Config - OpenAPI 3.0

This is the PingData Configuration API

The version of the OpenAPI document: 0.1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { EnummacSecretKeySchemaUrn } from './enummac-secret-key-schema-urn';

/**
 * 
 * @export
 * @interface MacSecretKeyResponseAllOf
 */
export interface MacSecretKeyResponseAllOf {
    /**
     * 
     * @type {Array<EnummacSecretKeySchemaUrn>}
     * @memberof MacSecretKeyResponseAllOf
     */
    'schemas'?: Array<EnummacSecretKeySchemaUrn>;
    /**
     * Name of the Mac Secret Key
     * @type {string}
     * @memberof MacSecretKeyResponseAllOf
     */
    'id'?: string;
    /**
     * The algorithm name used to generate this MAC key, e.g. HmacMD5, HmacSHA1, HMacSHA256, etc.
     * @type {string}
     * @memberof MacSecretKeyResponseAllOf
     */
    'macAlgorithmName'?: string;
    /**
     * The unique system-generated identifier for the Secret Key.
     * @type {string}
     * @memberof MacSecretKeyResponseAllOf
     */
    'keyID'?: string;
    /**
     * If the key is compromised, an administrator may set this flag to immediately trigger the creation of a new secret key. After the new key is generated, the value of this property will be reset to false.
     * @type {boolean}
     * @memberof MacSecretKeyResponseAllOf
     */
    'isCompromised'?: boolean;
    /**
     * The symmetric key that is used for both encryption of plain text and decryption of cipher text. This stores the secret key for each server instance encrypted with that server\'s inter-server certificate.
     * @type {Array<string>}
     * @memberof MacSecretKeyResponseAllOf
     */
    'symmetricKey'?: Array<string>;
    /**
     * The length of the key in bits.
     * @type {number}
     * @memberof MacSecretKeyResponseAllOf
     */
    'keyLengthBits'?: number;
}

