/*
PingData Config - OpenAPI 3.0

This is the PingData Configuration API

The version of the OpenAPI document: 0.1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { EnumexternalServerDefunctConnectionResultCodeProp } from './enumexternal-server-defunct-connection-result-code-prop';
import { EnumexternalServerMetricsEngineAuthenticationMethodProp } from './enumexternal-server-metrics-engine-authentication-method-prop';
import { EnumexternalServerMetricsEngineConnectionSecurityProp } from './enumexternal-server-metrics-engine-connection-security-prop';
import { EnumexternalServerVerifyCredentialsMethodProp } from './enumexternal-server-verify-credentials-method-prop';
import { EnummetricsEngineExternalServerSchemaUrn } from './enummetrics-engine-external-server-schema-urn';
import { Meta } from './meta';
import { MetaMeta } from './meta-meta';
import { MetaUrnPingidentitySchemasConfigurationMessages20 } from './meta-urn-pingidentity-schemas-configuration-messages20';
import { MetricsEngineExternalServerResponseAllOf } from './metrics-engine-external-server-response-all-of';

/**
 * @type MetricsEngineExternalServerResponse
 * @export
 */
export type MetricsEngineExternalServerResponse = Meta & MetricsEngineExternalServerResponseAllOf;


