/*
PingData Config - OpenAPI 3.0

This is the PingData Configuration API

The version of the OpenAPI document: 0.1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { EnumbackendWritabilityModeProp } from './enumbackend-writability-mode-prop';
import { EnummetricsBackendSchemaUrn } from './enummetrics-backend-schema-urn';

/**
 * 
 * @export
 * @interface MetricsBackendResponseAllOf
 */
export interface MetricsBackendResponseAllOf {
    /**
     * A description for this Backend
     * @type {string}
     * @memberof MetricsBackendResponseAllOf
     */
    'description'?: string;
    /**
     * 
     * @type {Array<EnummetricsBackendSchemaUrn>}
     * @memberof MetricsBackendResponseAllOf
     */
    'schemas'?: Array<EnummetricsBackendSchemaUrn>;
    /**
     * Name of the Backend
     * @type {string}
     * @memberof MetricsBackendResponseAllOf
     */
    'id'?: string;
    /**
     * Specifies a name to identify the associated backend.
     * @type {string}
     * @memberof MetricsBackendResponseAllOf
     */
    'backendID'?: string;
    /**
     * Specifies the path to the directory that will be used to store queued samples.
     * @type {string}
     * @memberof MetricsBackendResponseAllOf
     */
    'storageDir'?: string;
    /**
     * Specifies the path to the directory that contains metric definitions.
     * @type {string}
     * @memberof MetricsBackendResponseAllOf
     */
    'metricsDir'?: string;
    /**
     * Period when samples are flushed to disk.
     * @type {string}
     * @memberof MetricsBackendResponseAllOf
     */
    'sampleFlushInterval'?: string;
    /**
     * The retention policy to use for the Metrics Backend .
     * @type {Array<string>}
     * @memberof MetricsBackendResponseAllOf
     */
    'retentionPolicy'?: Array<string>;
    /**
     * Indicates whether the backend is enabled in the server.
     * @type {boolean}
     * @memberof MetricsBackendResponseAllOf
     */
    'enabled'?: boolean;
    /**
     * Specifies the behavior that the backend should use when processing write operations.
     * @type {EnumbackendWritabilityModeProp}
     * @memberof MetricsBackendResponseAllOf
     */
    'writabilityMode'?: EnumbackendWritabilityModeProp;
    /**
     * Determines whether any LDAP operation that would use this Backend is to return UNAVAILABLE when this Backend is disabled.
     * @type {boolean}
     * @memberof MetricsBackendResponseAllOf
     */
    'returnUnavailableWhenDisabled'?: boolean;
    /**
     * Specifies a notification manager for changes resulting from operations processed through this Backend
     * @type {string}
     * @memberof MetricsBackendResponseAllOf
     */
    'notificationManager'?: string;
}

