/*
PingData Config - OpenAPI 3.0

This is the PingData Configuration API

The version of the OpenAPI document: 0.1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { EnumneverRotateLogRotationPolicySchemaUrn } from './enumnever-rotate-log-rotation-policy-schema-urn';

/**
 * 
 * @export
 * @interface NeverRotateLogRotationPolicyShared
 */
export interface NeverRotateLogRotationPolicyShared {
    /**
     * A description for this Log Rotation Policy
     * @type {string}
     * @memberof NeverRotateLogRotationPolicyShared
     */
    'description'?: string;
    /**
     * 
     * @type {Array<EnumneverRotateLogRotationPolicySchemaUrn>}
     * @memberof NeverRotateLogRotationPolicyShared
     */
    'schemas': Array<EnumneverRotateLogRotationPolicySchemaUrn>;
}

