/*
PingData Config - OpenAPI 3.0

This is the PingData Configuration API

The version of the OpenAPI document: 0.1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { EnumnoOperationFailureLockoutActionSchemaUrn } from './enumno-operation-failure-lockout-action-schema-urn';

/**
 * 
 * @export
 * @interface NoOperationFailureLockoutActionShared
 */
export interface NoOperationFailureLockoutActionShared {
    /**
     * A description for this Failure Lockout Action
     * @type {string}
     * @memberof NoOperationFailureLockoutActionShared
     */
    'description'?: string;
    /**
     * 
     * @type {Array<EnumnoOperationFailureLockoutActionSchemaUrn>}
     * @memberof NoOperationFailureLockoutActionShared
     */
    'schemas': Array<EnumnoOperationFailureLockoutActionSchemaUrn>;
    /**
     * Indicates whether to generate an account status notification for cases in which this failure lockout action is invoked for a bind attempt with too many outstanding authentication failures.
     * @type {boolean}
     * @memberof NoOperationFailureLockoutActionShared
     */
    'generateAccountStatusNotification'?: boolean;
}

