/*
PingData Config - OpenAPI 3.0

This is the PingData Configuration API

The version of the OpenAPI document: 0.1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ThirdPartyNotificationManagerResponse } from './third-party-notification-manager-response';

/**
 * 
 * @export
 * @interface NotificationManagerListResponse
 */
export interface NotificationManagerListResponse {
    /**
     * 
     * @type {Array<string>}
     * @memberof NotificationManagerListResponse
     */
    'schemas'?: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof NotificationManagerListResponse
     */
    'totalResults'?: number;
    /**
     * 
     * @type {Array<ThirdPartyNotificationManagerResponse>}
     * @memberof NotificationManagerListResponse
     */
    'Resources'?: Array<ThirdPartyNotificationManagerResponse>;
}

