/*
PingData Config - OpenAPI 3.0

This is the PingData Configuration API

The version of the OpenAPI document: 0.1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { EnumobscuredValueSchemaUrn } from './enumobscured-value-schema-urn';

/**
 * 
 * @export
 * @interface ObscuredValueShared
 */
export interface ObscuredValueShared {
    /**
     * A description for this Obscured Value
     * @type {string}
     * @memberof ObscuredValueShared
     */
    'description'?: string;
    /**
     * 
     * @type {Array<EnumobscuredValueSchemaUrn>}
     * @memberof ObscuredValueShared
     */
    'schemas'?: Array<EnumobscuredValueSchemaUrn>;
    /**
     * The value to be stored in an obscured form.
     * @type {string}
     * @memberof ObscuredValueShared
     */
    'obscuredValue': string;
}

