/*
PingData Config - OpenAPI 3.0

This is the PingData Configuration API

The version of the OpenAPI document: 0.1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { EnumalertHandlerDisabledAlertTypeProp } from './enumalert-handler-disabled-alert-type-prop';
import { EnumalertHandlerEnabledAlertSeverityProp } from './enumalert-handler-enabled-alert-severity-prop';
import { EnumalertHandlerEnabledAlertTypeProp } from './enumalert-handler-enabled-alert-type-prop';
import { EnumalertHandlerOutputFormatProp } from './enumalert-handler-output-format-prop';
import { EnumalertHandlerOutputLocationProp } from './enumalert-handler-output-location-prop';
import { EnumoutputAlertHandlerSchemaUrn } from './enumoutput-alert-handler-schema-urn';
import { Meta } from './meta';
import { MetaMeta } from './meta-meta';
import { MetaUrnPingidentitySchemasConfigurationMessages20 } from './meta-urn-pingidentity-schemas-configuration-messages20';
import { OutputAlertHandlerResponseAllOf } from './output-alert-handler-response-all-of';

/**
 * @type OutputAlertHandlerResponse
 * @export
 */
export type OutputAlertHandlerResponse = Meta & OutputAlertHandlerResponseAllOf;


