/*
PingData Config - OpenAPI 3.0

This is the PingData Configuration API

The version of the OpenAPI document: 0.1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { EnumpasswordPolicyStateJsonVirtualAttributeSchemaUrn } from './enumpassword-policy-state-json-virtual-attribute-schema-urn';
import { Meta } from './meta';
import { MetaMeta } from './meta-meta';
import { MetaUrnPingidentitySchemasConfigurationMessages20 } from './meta-urn-pingidentity-schemas-configuration-messages20';
import { MirrorVirtualAttributeResponseAllOf } from './mirror-virtual-attribute-response-all-of';
import { PasswordPolicyStateJsonVirtualAttributeShared } from './password-policy-state-json-virtual-attribute-shared';

/**
 * @type PasswordPolicyStateJsonVirtualAttributeResponse
 * @export
 */
export type PasswordPolicyStateJsonVirtualAttributeResponse = Meta & MirrorVirtualAttributeResponseAllOf & PasswordPolicyStateJsonVirtualAttributeShared;


