/*
PingData Config - OpenAPI 3.0

This is the PingData Configuration API

The version of the OpenAPI document: 0.1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Argon2dPasswordStorageSchemeResponseAllOf } from './argon2d-password-storage-scheme-response-all-of';
import { EnumpasswordStorageSchemeDigestAlgorithmProp } from './enumpassword-storage-scheme-digest-algorithm-prop';
import { Enumpbkdf2PasswordStorageSchemeSchemaUrn } from './enumpbkdf2-password-storage-scheme-schema-urn';
import { Meta } from './meta';
import { MetaMeta } from './meta-meta';
import { MetaUrnPingidentitySchemasConfigurationMessages20 } from './meta-urn-pingidentity-schemas-configuration-messages20';
import { Pbkdf2PasswordStorageSchemeShared } from './pbkdf2-password-storage-scheme-shared';

/**
 * @type Pbkdf2PasswordStorageSchemeResponse
 * @export
 */
export type Pbkdf2PasswordStorageSchemeResponse = Argon2dPasswordStorageSchemeResponseAllOf & Meta & Pbkdf2PasswordStorageSchemeShared;


