/*
PingData Config - OpenAPI 3.0

This is the PingData Configuration API

The version of the OpenAPI document: 0.1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { EnumpingOnePassThroughAuthenticationHandlerSchemaUrn } from './enumping-one-pass-through-authentication-handler-schema-urn';
import { Meta } from './meta';
import { MetaMeta } from './meta-meta';
import { MetaUrnPingidentitySchemasConfigurationMessages20 } from './meta-urn-pingidentity-schemas-configuration-messages20';
import { PingOnePassThroughAuthenticationHandlerResponseAllOf } from './ping-one-pass-through-authentication-handler-response-all-of';
import { PingOnePassThroughAuthenticationHandlerShared } from './ping-one-pass-through-authentication-handler-shared';

/**
 * @type PingOnePassThroughAuthenticationHandlerResponse
 * @export
 */
export type PingOnePassThroughAuthenticationHandlerResponse = Meta & PingOnePassThroughAuthenticationHandlerResponseAllOf & PingOnePassThroughAuthenticationHandlerShared;


