/*
PingData Config - OpenAPI 3.0

This is the PingData Configuration API

The version of the OpenAPI document: 0.1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { EnumpluginProfileActionProp } from './enumplugin-profile-action-prop';
import { EnumprofilerPluginSchemaUrn } from './enumprofiler-plugin-schema-urn';

/**
 * 
 * @export
 * @interface ProfilerPluginResponseAllOf
 */
export interface ProfilerPluginResponseAllOf {
    /**
     * A description for this Plugin
     * @type {string}
     * @memberof ProfilerPluginResponseAllOf
     */
    'description'?: string;
    /**
     * 
     * @type {Array<EnumprofilerPluginSchemaUrn>}
     * @memberof ProfilerPluginResponseAllOf
     */
    'schemas'?: Array<EnumprofilerPluginSchemaUrn>;
    /**
     * Name of the Plugin
     * @type {string}
     * @memberof ProfilerPluginResponseAllOf
     */
    'id'?: string;
    /**
     * Specifies the sample interval in milliseconds to be used when capturing profiling information in the server.
     * @type {string}
     * @memberof ProfilerPluginResponseAllOf
     */
    'profileSampleInterval'?: string;
    /**
     * Specifies the path to the directory where profile information is to be written. This path may be either an absolute path or a path that is relative to the root of the Directory Server instance.
     * @type {string}
     * @memberof ProfilerPluginResponseAllOf
     */
    'profileDirectory'?: string;
    /**
     * Indicates whether the profiler plug-in is to start collecting data automatically when the Directory Server is started.
     * @type {boolean}
     * @memberof ProfilerPluginResponseAllOf
     */
    'enableProfilingOnStartup'?: boolean;
    /**
     * Specifies the action that should be taken by the profiler.
     * @type {EnumpluginProfileActionProp}
     * @memberof ProfilerPluginResponseAllOf
     */
    'profileAction'?: EnumpluginProfileActionProp;
    /**
     * Indicates whether the plug-in is enabled for use.
     * @type {boolean}
     * @memberof ProfilerPluginResponseAllOf
     */
    'enabled'?: boolean;
}

