/*
PingData Config - OpenAPI 3.0

This is the PingData Configuration API

The version of the OpenAPI document: 0.1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { RecurringTaskChainResponse } from './recurring-task-chain-response';

/**
 * 
 * @export
 * @interface RecurringTaskChainListResponse
 */
export interface RecurringTaskChainListResponse {
    /**
     * 
     * @type {Array<string>}
     * @memberof RecurringTaskChainListResponse
     */
    'schemas'?: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof RecurringTaskChainListResponse
     */
    'totalResults'?: number;
    /**
     * 
     * @type {Array<RecurringTaskChainResponse>}
     * @memberof RecurringTaskChainListResponse
     */
    'Resources'?: Array<RecurringTaskChainResponse>;
}

