/*
PingData Config - OpenAPI 3.0

This is the PingData Configuration API

The version of the OpenAPI document: 0.1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { EnumrecurringTaskChainInterruptedByShutdownBehaviorProp } from './enumrecurring-task-chain-interrupted-by-shutdown-behavior-prop';
import { EnumrecurringTaskChainScheduledDateSelectionTypeProp } from './enumrecurring-task-chain-scheduled-date-selection-type-prop';
import { EnumrecurringTaskChainScheduledDayOfTheMonthProp } from './enumrecurring-task-chain-scheduled-day-of-the-month-prop';
import { EnumrecurringTaskChainScheduledDayOfTheWeekProp } from './enumrecurring-task-chain-scheduled-day-of-the-week-prop';
import { EnumrecurringTaskChainScheduledMonthProp } from './enumrecurring-task-chain-scheduled-month-prop';
import { EnumrecurringTaskChainSchemaUrn } from './enumrecurring-task-chain-schema-urn';
import { EnumrecurringTaskChainServerOfflineAtStartTimeBehaviorProp } from './enumrecurring-task-chain-server-offline-at-start-time-behavior-prop';
import { Meta } from './meta';
import { MetaMeta } from './meta-meta';
import { MetaUrnPingidentitySchemasConfigurationMessages20 } from './meta-urn-pingidentity-schemas-configuration-messages20';
import { RecurringTaskChainResponseAllOf } from './recurring-task-chain-response-all-of';
import { RecurringTaskChainShared } from './recurring-task-chain-shared';

/**
 * @type RecurringTaskChainResponse
 * @export
 */
export type RecurringTaskChainResponse = Meta & RecurringTaskChainResponseAllOf & RecurringTaskChainShared;


