/*
PingData Config - OpenAPI 3.0

This is the PingData Configuration API

The version of the OpenAPI document: 0.1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { EnumreplicationDomainMissingChangesPolicyProp } from './enumreplication-domain-missing-changes-policy-prop';
import { EnumreplicationDomainSchemaUrn } from './enumreplication-domain-schema-urn';
import { Meta } from './meta';
import { MetaMeta } from './meta-meta';
import { MetaUrnPingidentitySchemasConfigurationMessages20 } from './meta-urn-pingidentity-schemas-configuration-messages20';
import { ReplicationDomainResponseAllOf } from './replication-domain-response-all-of';

/**
 * @type ReplicationDomainResponse
 * @export
 */
export type ReplicationDomainResponse = Meta & ReplicationDomainResponseAllOf;


