/*
PingData Config - OpenAPI 3.0

This is the PingData Configuration API

The version of the OpenAPI document: 0.1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { EnumsaltedMd5PasswordStorageSchemeSchemaUrn } from './enumsalted-md5-password-storage-scheme-schema-urn';
import { Meta } from './meta';
import { MetaMeta } from './meta-meta';
import { MetaUrnPingidentitySchemasConfigurationMessages20 } from './meta-urn-pingidentity-schemas-configuration-messages20';
import { SaltedMd5PasswordStorageSchemeResponseAllOf } from './salted-md5-password-storage-scheme-response-all-of';

/**
 * @type SaltedMd5PasswordStorageSchemeResponse
 * @export
 */
export type SaltedMd5PasswordStorageSchemeResponse = Meta & SaltedMd5PasswordStorageSchemeResponseAllOf;


