/*
PingData Config - OpenAPI 3.0

This is the PingData Configuration API

The version of the OpenAPI document: 0.1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { EnumsaltedMd5PasswordStorageSchemeSchemaUrn } from './enumsalted-md5-password-storage-scheme-schema-urn';

/**
 * 
 * @export
 * @interface SaltedMd5PasswordStorageSchemeResponseAllOf
 */
export interface SaltedMd5PasswordStorageSchemeResponseAllOf {
    /**
     * A description for this Password Storage Scheme
     * @type {string}
     * @memberof SaltedMd5PasswordStorageSchemeResponseAllOf
     */
    'description'?: string;
    /**
     * 
     * @type {Array<EnumsaltedMd5PasswordStorageSchemeSchemaUrn>}
     * @memberof SaltedMd5PasswordStorageSchemeResponseAllOf
     */
    'schemas'?: Array<EnumsaltedMd5PasswordStorageSchemeSchemaUrn>;
    /**
     * Name of the Password Storage Scheme
     * @type {string}
     * @memberof SaltedMd5PasswordStorageSchemeResponseAllOf
     */
    'id'?: string;
    /**
     * Indicates whether the Salted MD5 Password Storage Scheme is enabled for use.
     * @type {boolean}
     * @memberof SaltedMd5PasswordStorageSchemeResponseAllOf
     */
    'enabled'?: boolean;
    /**
     * Specifies the number of bytes to use for the generated salt.
     * @type {number}
     * @memberof SaltedMd5PasswordStorageSchemeResponseAllOf
     */
    'saltLengthBytes'?: number;
}

