/*
PingData Config - OpenAPI 3.0

This is the PingData Configuration API

The version of the OpenAPI document: 0.1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { EnumbackendWritabilityModeProp } from './enumbackend-writability-mode-prop';
import { EnumschemaBackendSchemaUrn } from './enumschema-backend-schema-urn';

/**
 * 
 * @export
 * @interface SchemaBackendResponseAllOf
 */
export interface SchemaBackendResponseAllOf {
    /**
     * A description for this Backend
     * @type {string}
     * @memberof SchemaBackendResponseAllOf
     */
    'description'?: string;
    /**
     * 
     * @type {Array<EnumschemaBackendSchemaUrn>}
     * @memberof SchemaBackendResponseAllOf
     */
    'schemas'?: Array<EnumschemaBackendSchemaUrn>;
    /**
     * Name of the Backend
     * @type {string}
     * @memberof SchemaBackendResponseAllOf
     */
    'id'?: string;
    /**
     * Specifies a name to identify the associated backend.
     * @type {string}
     * @memberof SchemaBackendResponseAllOf
     */
    'backendID'?: string;
    /**
     * Specifies the base DN(s) for the data that the backend handles.
     * @type {Array<string>}
     * @memberof SchemaBackendResponseAllOf
     */
    'baseDN'?: Array<string>;
    /**
     * Specifies the behavior that the backend should use when processing write operations.
     * @type {EnumbackendWritabilityModeProp}
     * @memberof SchemaBackendResponseAllOf
     */
    'writabilityMode'?: EnumbackendWritabilityModeProp;
    /**
     * Defines the base DNs of the subtrees in which the schema information is published in addition to the value included in the base-dn property.
     * @type {Array<string>}
     * @memberof SchemaBackendResponseAllOf
     */
    'schemaEntryDN'?: Array<string>;
    /**
     * Indicates whether to treat all attributes in the schema entry as if they were user attributes regardless of their configuration.
     * @type {boolean}
     * @memberof SchemaBackendResponseAllOf
     */
    'showAllAttributes'?: boolean;
    /**
     * Specifies the name of a file (which must exist in the config/schema directory) containing schema elements that should be considered read-only. Any schema definitions contained in read-only files cannot be altered by external clients.
     * @type {Array<string>}
     * @memberof SchemaBackendResponseAllOf
     */
    'readOnlySchemaFile'?: Array<string>;
    /**
     * Indicates whether the backend is enabled in the server.
     * @type {boolean}
     * @memberof SchemaBackendResponseAllOf
     */
    'enabled'?: boolean;
    /**
     * Determines whether the Directory Server enters a DEGRADED state (and sends a corresponding alert) when this Backend is disabled.
     * @type {boolean}
     * @memberof SchemaBackendResponseAllOf
     */
    'setDegradedAlertWhenDisabled'?: boolean;
    /**
     * Determines whether any LDAP operation that would use this Backend is to return UNAVAILABLE when this Backend is disabled.
     * @type {boolean}
     * @memberof SchemaBackendResponseAllOf
     */
    'returnUnavailableWhenDisabled'?: boolean;
    /**
     * Specifies the permissions that should be applied to files and directories created by a backup of the backend.
     * @type {string}
     * @memberof SchemaBackendResponseAllOf
     */
    'backupFilePermissions'?: string;
    /**
     * Specifies a notification manager for changes resulting from operations processed through this Backend
     * @type {string}
     * @memberof SchemaBackendResponseAllOf
     */
    'notificationManager'?: string;
}

