/*
PingData Config - OpenAPI 3.0

This is the PingData Configuration API

The version of the OpenAPI document: 0.1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { EnumsimpleSearchEntryCriteriaSchemaUrn } from './enumsimple-search-entry-criteria-schema-urn';
import { Meta } from './meta';
import { MetaMeta } from './meta-meta';
import { MetaUrnPingidentitySchemasConfigurationMessages20 } from './meta-urn-pingidentity-schemas-configuration-messages20';
import { SimpleSearchEntryCriteriaResponseAllOf } from './simple-search-entry-criteria-response-all-of';
import { SimpleSearchEntryCriteriaShared } from './simple-search-entry-criteria-shared';

/**
 * @type SimpleSearchEntryCriteriaResponse
 * @export
 */
export type SimpleSearchEntryCriteriaResponse = Meta & SimpleSearchEntryCriteriaResponseAllOf & SimpleSearchEntryCriteriaShared;


