/*
PingData Config - OpenAPI 3.0

This is the PingData Configuration API

The version of the OpenAPI document: 0.1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { EnumsubjectEqualsDnCertificateMapperSchemaUrn } from './enumsubject-equals-dn-certificate-mapper-schema-urn';

/**
 * 
 * @export
 * @interface SubjectEqualsDnCertificateMapperShared
 */
export interface SubjectEqualsDnCertificateMapperShared {
    /**
     * A description for this Certificate Mapper
     * @type {string}
     * @memberof SubjectEqualsDnCertificateMapperShared
     */
    'description'?: string;
    /**
     * 
     * @type {Array<EnumsubjectEqualsDnCertificateMapperSchemaUrn>}
     * @memberof SubjectEqualsDnCertificateMapperShared
     */
    'schemas': Array<EnumsubjectEqualsDnCertificateMapperSchemaUrn>;
    /**
     * Indicates whether the Certificate Mapper is enabled.
     * @type {boolean}
     * @memberof SubjectEqualsDnCertificateMapperShared
     */
    'enabled': boolean;
}

