/*
PingData Config - OpenAPI 3.0

This is the PingData Configuration API

The version of the OpenAPI document: 0.1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { EnumexternalServerTransportMechanismProp } from './enumexternal-server-transport-mechanism-prop';
import { EnumsyslogExternalServerSchemaUrn } from './enumsyslog-external-server-schema-urn';

/**
 * 
 * @export
 * @interface SyslogExternalServerShared
 */
export interface SyslogExternalServerShared {
    /**
     * A description for this External Server
     * @type {string}
     * @memberof SyslogExternalServerShared
     */
    'description'?: string;
    /**
     * 
     * @type {Array<EnumsyslogExternalServerSchemaUrn>}
     * @memberof SyslogExternalServerShared
     */
    'schemas': Array<EnumsyslogExternalServerSchemaUrn>;
    /**
     * The address of the syslog server.
     * @type {string}
     * @memberof SyslogExternalServerShared
     */
    'serverHostName': string;
    /**
     * The port on which the syslog server accepts connections.
     * @type {number}
     * @memberof SyslogExternalServerShared
     */
    'serverPort'?: number;
    /**
     * The transport mechanism that should be used when communicating with the syslog server.
     * @type {EnumexternalServerTransportMechanismProp}
     * @memberof SyslogExternalServerShared
     */
    'transportMechanism': EnumexternalServerTransportMechanismProp;
    /**
     * Specifies the maximum length of time to wait for a connection to be established before giving up and considering the server unavailable. This will only be used when communicating with the syslog server over TCP (with or without TLS encryption).
     * @type {string}
     * @memberof SyslogExternalServerShared
     */
    'connectTimeout'?: string;
    /**
     * The maximum length of time that TCP connections should remain established. This will be ignored for UDP-based connections. A zero duration indicates that no maximum age will be imposed.
     * @type {string}
     * @memberof SyslogExternalServerShared
     */
    'maxConnectionAge'?: string;
    /**
     * A trust manager provider that will be used to determine whether to trust the certificate chain presented by the syslog server when communication is encrypted with TLS. This property will be ignored when not using TLS encryption.
     * @type {string}
     * @memberof SyslogExternalServerShared
     */
    'trustManagerProvider'?: string;
}

