/*
PingData Config - OpenAPI 3.0

This is the PingData Configuration API

The version of the OpenAPI document: 0.1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { EnumlogPublisherDefaultSeverityProp } from './enumlog-publisher-default-severity-prop';
import { EnumlogPublisherLoggingErrorBehaviorProp } from './enumlog-publisher-logging-error-behavior-prop';
import { EnumlogPublisherSyslogFacilityProp } from './enumlog-publisher-syslog-facility-prop';
import { EnumlogPublisherSyslogSeverityProp } from './enumlog-publisher-syslog-severity-prop';
import { EnumsyslogJsonErrorLogPublisherSchemaUrn } from './enumsyslog-json-error-log-publisher-schema-urn';

/**
 * 
 * @export
 * @interface SyslogJsonErrorLogPublisherShared
 */
export interface SyslogJsonErrorLogPublisherShared {
    /**
     * A description for this Log Publisher
     * @type {string}
     * @memberof SyslogJsonErrorLogPublisherShared
     */
    'description'?: string;
    /**
     * 
     * @type {Array<EnumsyslogJsonErrorLogPublisherSchemaUrn>}
     * @memberof SyslogJsonErrorLogPublisherShared
     */
    'schemas': Array<EnumsyslogJsonErrorLogPublisherSchemaUrn>;
    /**
     * 
     * @type {Array<EnumlogPublisherDefaultSeverityProp>}
     * @memberof SyslogJsonErrorLogPublisherShared
     */
    'defaultSeverity'?: Array<EnumlogPublisherDefaultSeverityProp>;
    /**
     * The syslog server to which messages should be sent.
     * @type {Array<string>}
     * @memberof SyslogJsonErrorLogPublisherShared
     */
    'syslogExternalServer': Array<string>;
    /**
     * The syslog facility to use for the messages that are logged by this Syslog JSON Audit Log Publisher.
     * @type {EnumlogPublisherSyslogFacilityProp}
     * @memberof SyslogJsonErrorLogPublisherShared
     */
    'syslogFacility'?: EnumlogPublisherSyslogFacilityProp;
    /**
     * The syslog severity to use for the messages that are logged by this Syslog JSON Audit Log Publisher.
     * @type {EnumlogPublisherSyslogSeverityProp}
     * @memberof SyslogJsonErrorLogPublisherShared
     */
    'syslogSeverity'?: EnumlogPublisherSyslogSeverityProp;
    /**
     * The local host name that will be included in syslog messages that are logged by this Syslog JSON Error Log Publisher.
     * @type {string}
     * @memberof SyslogJsonErrorLogPublisherShared
     */
    'syslogMessageHostName'?: string;
    /**
     * The application name that will be included in syslog messages that are logged by this Syslog JSON Error Log Publisher.
     * @type {string}
     * @memberof SyslogJsonErrorLogPublisherShared
     */
    'syslogMessageApplicationName'?: string;
    /**
     * The maximum number of log records that can be stored in the asynchronous queue.
     * @type {number}
     * @memberof SyslogJsonErrorLogPublisherShared
     */
    'queueSize'?: number;
    /**
     * Indicates whether log messages should include the product name for the Directory Server.
     * @type {boolean}
     * @memberof SyslogJsonErrorLogPublisherShared
     */
    'includeProductName'?: boolean;
    /**
     * Indicates whether log messages should include the instance name for the Directory Server.
     * @type {boolean}
     * @memberof SyslogJsonErrorLogPublisherShared
     */
    'includeInstanceName'?: boolean;
    /**
     * Indicates whether log messages should include the startup ID for the Directory Server, which is a value assigned to the server instance at startup and may be used to identify when the server has been restarted.
     * @type {boolean}
     * @memberof SyslogJsonErrorLogPublisherShared
     */
    'includeStartupID'?: boolean;
    /**
     * Indicates whether log messages should include the thread ID for the Directory Server in each log message. This ID can be used to correlate log messages from the same thread within a single log as well as generated by the same thread across different types of log files. More information about the thread with a specific ID can be obtained using the cn=JVM Stack Trace,cn=monitor entry.
     * @type {boolean}
     * @memberof SyslogJsonErrorLogPublisherShared
     */
    'includeThreadID'?: boolean;
    /**
     * Indicates whether to use the generified version of the log message string (which may use placeholders like %s for a string or %d for an integer), rather than the version of the message with those placeholders replaced with specific values that would normally be written to the log.
     * @type {boolean}
     * @memberof SyslogJsonErrorLogPublisherShared
     */
    'generifyMessageStringsWhenPossible'?: boolean;
    /**
     * Specifies the override severity levels for the logger based on the category of the messages.
     * @type {Array<string>}
     * @memberof SyslogJsonErrorLogPublisherShared
     */
    'overrideSeverity'?: Array<string>;
    /**
     * Indicates whether the Log Publisher is enabled for use.
     * @type {boolean}
     * @memberof SyslogJsonErrorLogPublisherShared
     */
    'enabled': boolean;
    /**
     * Specifies the behavior that the server should exhibit if an error occurs during logging processing.
     * @type {EnumlogPublisherLoggingErrorBehaviorProp}
     * @memberof SyslogJsonErrorLogPublisherShared
     */
    'loggingErrorBehavior'?: EnumlogPublisherLoggingErrorBehaviorProp;
}

