/*
PingData Config - OpenAPI 3.0

This is the PingData Configuration API

The version of the OpenAPI document: 0.1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { EnumlogPublisherLoggingErrorBehaviorProp } from './enumlog-publisher-logging-error-behavior-prop';
import { EnumlogPublisherSyslogFacilityProp } from './enumlog-publisher-syslog-facility-prop';
import { EnumlogPublisherSyslogJsonAuditSoftDeleteEntryAuditBehaviorProp } from './enumlog-publisher-syslog-json-audit-soft-delete-entry-audit-behavior-prop';
import { EnumlogPublisherSyslogSeverityProp } from './enumlog-publisher-syslog-severity-prop';
import { EnumsyslogJsonAuditLogPublisherSchemaUrn } from './enumsyslog-json-audit-log-publisher-schema-urn';
import { Meta } from './meta';
import { MetaMeta } from './meta-meta';
import { MetaUrnPingidentitySchemasConfigurationMessages20 } from './meta-urn-pingidentity-schemas-configuration-messages20';
import { SyslogJsonAuditLogPublisherResponseAllOf } from './syslog-json-audit-log-publisher-response-all-of';
import { SyslogJsonAuditLogPublisherShared } from './syslog-json-audit-log-publisher-shared';

/**
 * @type SyslogJsonAuditLogPublisherResponse
 * @export
 */
export type SyslogJsonAuditLogPublisherResponse = Meta & SyslogJsonAuditLogPublisherResponseAllOf & SyslogJsonAuditLogPublisherShared;


