/*
PingData Config - OpenAPI 3.0

This is the PingData Configuration API

The version of the OpenAPI document: 0.1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { EnumlogPublisherLoggingErrorBehaviorProp } from './enumlog-publisher-logging-error-behavior-prop';
import { EnumlogPublisherSyslogFacilityProp } from './enumlog-publisher-syslog-facility-prop';
import { EnumlogPublisherSyslogSeverityProp } from './enumlog-publisher-syslog-severity-prop';
import { EnumlogPublisherTimestampPrecisionProp } from './enumlog-publisher-timestamp-precision-prop';
import { EnumsyslogTextAccessLogPublisherSchemaUrn } from './enumsyslog-text-access-log-publisher-schema-urn';
import { Meta } from './meta';
import { MetaMeta } from './meta-meta';
import { MetaUrnPingidentitySchemasConfigurationMessages20 } from './meta-urn-pingidentity-schemas-configuration-messages20';
import { SyslogJsonAuditLogPublisherResponseAllOf } from './syslog-json-audit-log-publisher-response-all-of';
import { SyslogTextAccessLogPublisherShared } from './syslog-text-access-log-publisher-shared';

/**
 * @type SyslogTextAccessLogPublisherResponse
 * @export
 */
export type SyslogTextAccessLogPublisherResponse = Meta & SyslogJsonAuditLogPublisherResponseAllOf & SyslogTextAccessLogPublisherShared;


