/*
PingData Config - OpenAPI 3.0

This is the PingData Configuration API

The version of the OpenAPI document: 0.1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { EnumthirdPartySearchReferenceCriteriaSchemaUrn } from './enumthird-party-search-reference-criteria-schema-urn';
import { Meta } from './meta';
import { MetaMeta } from './meta-meta';
import { MetaUrnPingidentitySchemasConfigurationMessages20 } from './meta-urn-pingidentity-schemas-configuration-messages20';
import { SimpleSearchReferenceCriteriaResponseAllOf } from './simple-search-reference-criteria-response-all-of';
import { ThirdPartySearchReferenceCriteriaShared } from './third-party-search-reference-criteria-shared';

/**
 * @type ThirdPartySearchReferenceCriteriaResponse
 * @export
 */
export type ThirdPartySearchReferenceCriteriaResponse = Meta & SimpleSearchReferenceCriteriaResponseAllOf & ThirdPartySearchReferenceCriteriaShared;


