/*
PingData Config - OpenAPI 3.0

This is the PingData Configuration API

The version of the OpenAPI document: 0.1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { EnumthirdPartyPostLdifExportTaskProcessorSchemaUrn } from './enumthird-party-post-ldif-export-task-processor-schema-urn';

/**
 * 
 * @export
 * @interface ThirdPartyPostLdifExportTaskProcessorShared
 */
export interface ThirdPartyPostLdifExportTaskProcessorShared {
    /**
     * A description for this Post LDIF Export Task Processor
     * @type {string}
     * @memberof ThirdPartyPostLdifExportTaskProcessorShared
     */
    'description'?: string;
    /**
     * 
     * @type {Array<EnumthirdPartyPostLdifExportTaskProcessorSchemaUrn>}
     * @memberof ThirdPartyPostLdifExportTaskProcessorShared
     */
    'schemas': Array<EnumthirdPartyPostLdifExportTaskProcessorSchemaUrn>;
    /**
     * The fully-qualified name of the Java class providing the logic for the Third Party Post LDIF Export Task Processor.
     * @type {string}
     * @memberof ThirdPartyPostLdifExportTaskProcessorShared
     */
    'extensionClass': string;
    /**
     * The set of arguments used to customize the behavior for the Third Party Post LDIF Export Task Processor. Each configuration property should be given in the form \'name=value\'.
     * @type {Array<string>}
     * @memberof ThirdPartyPostLdifExportTaskProcessorShared
     */
    'extensionArgument'?: Array<string>;
    /**
     * Indicates whether the Post LDIF Export Task Processor is enabled for use.
     * @type {boolean}
     * @memberof ThirdPartyPostLdifExportTaskProcessorShared
     */
    'enabled': boolean;
}

