/*
PingData Config - OpenAPI 3.0

This is the PingData Configuration API

The version of the OpenAPI document: 0.1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { EnumtraditionalWorkQueueSchemaUrn } from './enumtraditional-work-queue-schema-urn';

/**
 * 
 * @export
 * @interface TraditionalWorkQueueResponseAllOf
 */
export interface TraditionalWorkQueueResponseAllOf {
    /**
     * 
     * @type {Array<EnumtraditionalWorkQueueSchemaUrn>}
     * @memberof TraditionalWorkQueueResponseAllOf
     */
    'schemas'?: Array<EnumtraditionalWorkQueueSchemaUrn>;
    /**
     * Specifies the number of worker threads to be used for processing operations placed in the queue.
     * @type {number}
     * @memberof TraditionalWorkQueueResponseAllOf
     */
    'numWorkerThreads'?: number;
    /**
     * Specifies the maximum number of queued operations that can be in the work queue at any given time.
     * @type {number}
     * @memberof TraditionalWorkQueueResponseAllOf
     */
    'maxWorkQueueCapacity'?: number;
}

