/*
PingData Config - OpenAPI 3.0

This is the PingData Configuration API

The version of the OpenAPI document: 0.1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { EnumtraditionalWorkQueueSchemaUrn } from './enumtraditional-work-queue-schema-urn';
import { Meta } from './meta';
import { MetaMeta } from './meta-meta';
import { MetaUrnPingidentitySchemasConfigurationMessages20 } from './meta-urn-pingidentity-schemas-configuration-messages20';
import { TraditionalWorkQueueResponseAllOf } from './traditional-work-queue-response-all-of';

/**
 * @type TraditionalWorkQueueResponse
 * @export
 */
export type TraditionalWorkQueueResponse = Meta & TraditionalWorkQueueResponseAllOf;


