/*
PingData Config - OpenAPI 3.0

This is the PingData Configuration API

The version of the OpenAPI document: 0.1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { EnumbackendWritabilityModeProp } from './enumbackend-writability-mode-prop';
import { EnumtrustStoreBackendSchemaUrn } from './enumtrust-store-backend-schema-urn';

/**
 * 
 * @export
 * @interface TrustStoreBackendResponseAllOf
 */
export interface TrustStoreBackendResponseAllOf {
    /**
     * A description for this Backend
     * @type {string}
     * @memberof TrustStoreBackendResponseAllOf
     */
    'description'?: string;
    /**
     * 
     * @type {Array<EnumtrustStoreBackendSchemaUrn>}
     * @memberof TrustStoreBackendResponseAllOf
     */
    'schemas'?: Array<EnumtrustStoreBackendSchemaUrn>;
    /**
     * Name of the Backend
     * @type {string}
     * @memberof TrustStoreBackendResponseAllOf
     */
    'id'?: string;
    /**
     * Specifies a name to identify the associated backend.
     * @type {string}
     * @memberof TrustStoreBackendResponseAllOf
     */
    'backendID'?: string;
    /**
     * Specifies the base DN(s) for the data that the backend handles.
     * @type {Array<string>}
     * @memberof TrustStoreBackendResponseAllOf
     */
    'baseDN'?: Array<string>;
    /**
     * Specifies the behavior that the backend should use when processing write operations.
     * @type {EnumbackendWritabilityModeProp}
     * @memberof TrustStoreBackendResponseAllOf
     */
    'writabilityMode'?: EnumbackendWritabilityModeProp;
    /**
     * Specifies the path to the file that stores the trust information.
     * @type {string}
     * @memberof TrustStoreBackendResponseAllOf
     */
    'trustStoreFile'?: string;
    /**
     * Specifies the format for the data in the key store file.
     * @type {string}
     * @memberof TrustStoreBackendResponseAllOf
     */
    'trustStoreType'?: string;
    /**
     * Specifies the clear-text PIN needed to access the Trust Store Backend.
     * @type {string}
     * @memberof TrustStoreBackendResponseAllOf
     */
    'trustStorePin'?: string;
    /**
     * Specifies the path to the text file whose only contents should be a single line containing the clear-text PIN needed to access the Trust Store Backend.
     * @type {string}
     * @memberof TrustStoreBackendResponseAllOf
     */
    'trustStorePinFile'?: string;
    /**
     * The passphrase provider to use to obtain the clear-text PIN needed to access the Trust Store Backend.
     * @type {string}
     * @memberof TrustStoreBackendResponseAllOf
     */
    'trustStorePinPassphraseProvider'?: string;
    /**
     * Indicates whether the backend is enabled in the server.
     * @type {boolean}
     * @memberof TrustStoreBackendResponseAllOf
     */
    'enabled'?: boolean;
    /**
     * Determines whether the Directory Server enters a DEGRADED state (and sends a corresponding alert) when this Backend is disabled.
     * @type {boolean}
     * @memberof TrustStoreBackendResponseAllOf
     */
    'setDegradedAlertWhenDisabled'?: boolean;
    /**
     * Determines whether any LDAP operation that would use this Backend is to return UNAVAILABLE when this Backend is disabled.
     * @type {boolean}
     * @memberof TrustStoreBackendResponseAllOf
     */
    'returnUnavailableWhenDisabled'?: boolean;
    /**
     * Specifies the permissions that should be applied to files and directories created by a backup of the backend.
     * @type {string}
     * @memberof TrustStoreBackendResponseAllOf
     */
    'backupFilePermissions'?: string;
    /**
     * Specifies a notification manager for changes resulting from operations processed through this Backend
     * @type {string}
     * @memberof TrustStoreBackendResponseAllOf
     */
    'notificationManager'?: string;
}

