/*
PingData Config - OpenAPI 3.0

This is the PingData Configuration API

The version of the OpenAPI document: 0.1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { EnumtrustedCertificateSchemaUrn } from './enumtrusted-certificate-schema-urn';
import { Meta } from './meta';
import { MetaMeta } from './meta-meta';
import { MetaUrnPingidentitySchemasConfigurationMessages20 } from './meta-urn-pingidentity-schemas-configuration-messages20';
import { TrustedCertificateResponseAllOf } from './trusted-certificate-response-all-of';
import { TrustedCertificateShared } from './trusted-certificate-shared';

/**
 * @type TrustedCertificateResponse
 * @export
 */
export type TrustedCertificateResponse = Meta & TrustedCertificateResponseAllOf & TrustedCertificateShared;


