/*
PingData Config - OpenAPI 3.0

This is the PingData Configuration API

The version of the OpenAPI document: 0.1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { EnumvirtualStaticGroupImplementationSchemaUrn } from './enumvirtual-static-group-implementation-schema-urn';

/**
 * 
 * @export
 * @interface VirtualStaticGroupImplementationResponseAllOf
 */
export interface VirtualStaticGroupImplementationResponseAllOf {
    /**
     * A description for this Group Implementation
     * @type {string}
     * @memberof VirtualStaticGroupImplementationResponseAllOf
     */
    'description'?: string;
    /**
     * 
     * @type {Array<EnumvirtualStaticGroupImplementationSchemaUrn>}
     * @memberof VirtualStaticGroupImplementationResponseAllOf
     */
    'schemas'?: Array<EnumvirtualStaticGroupImplementationSchemaUrn>;
    /**
     * Name of the Group Implementation
     * @type {string}
     * @memberof VirtualStaticGroupImplementationResponseAllOf
     */
    'id'?: string;
    /**
     * Indicates whether the Group Implementation is enabled.
     * @type {boolean}
     * @memberof VirtualStaticGroupImplementationResponseAllOf
     */
    'enabled'?: boolean;
}

