/*
PingData Config - OpenAPI 3.0

This is the PingData Configuration API

The version of the OpenAPI document: 0.1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { EnumdataSecurityAuditorAuditSeverityProp } from './enumdata-security-auditor-audit-severity-prop';
import { EnumdataSecurityAuditorWeakCryptEncodingProp } from './enumdata-security-auditor-weak-crypt-encoding-prop';
import { EnumweaklyEncodedPasswordDataSecurityAuditorSchemaUrn } from './enumweakly-encoded-password-data-security-auditor-schema-urn';
import { ExpiredPasswordDataSecurityAuditorResponseAllOf } from './expired-password-data-security-auditor-response-all-of';
import { Meta } from './meta';
import { MetaMeta } from './meta-meta';
import { MetaUrnPingidentitySchemasConfigurationMessages20 } from './meta-urn-pingidentity-schemas-configuration-messages20';
import { WeaklyEncodedPasswordDataSecurityAuditorShared } from './weakly-encoded-password-data-security-auditor-shared';

/**
 * @type WeaklyEncodedPasswordDataSecurityAuditorResponse
 * @export
 */
export type WeaklyEncodedPasswordDataSecurityAuditorResponse = ExpiredPasswordDataSecurityAuditorResponseAllOf & Meta & WeaklyEncodedPasswordDataSecurityAuditorShared;


